# Generated by Django 5.1.2 on 2024-11-07 11:50

import autoslug.fields
import common.fields
import django.db.models.deletion
import enumerify.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    enumerify.fields.SelectIntegerField(
                        choices=[
                            (0, "Active"),
                            (1, "Inactive"),
                            (2, "Draft"),
                            (3, "Released"),
                            (4, "Approved Draft"),
                            (5, "Absent"),
                            (6, "Purchase Order"),
                            (7, "Suspend"),
                            (8, "On Hold"),
                            (9, "Hardwired"),
                            (10, "Loss"),
                            (11, "Freeze"),
                            (12, "For Adjustment"),
                            (13, "Distributor Order"),
                        ],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        allow_unicode=True,
                        always_update=True,
                        editable=False,
                        populate_from="name",
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "logo",
                    common.fields.TimestampThumbnailImageField(
                        blank=True, null=True, upload_to="organization/logo"
                    ),
                ),
                (
                    "profile_image",
                    common.fields.TimestampThumbnailImageField(
                        blank=True, null=True, upload_to="organization/profile"
                    ),
                ),
                (
                    "hero_image",
                    common.fields.TimestampThumbnailImageField(
                        blank=True, null=True, upload_to="organization/hero"
                    ),
                ),
                ("primary_mobile", models.CharField(max_length=20)),
                (
                    "other_contact",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("contact_person", models.CharField(max_length=64)),
                ("website", models.URLField(blank=True, null=True)),
                ("contact_person_designation", models.CharField(max_length=64)),
                ("license_no", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "license_image",
                    common.fields.TimestampThumbnailImageField(
                        blank=True, null=True, upload_to="organization/license"
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizationUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    enumerify.fields.SelectIntegerField(
                        choices=[
                            (0, "Active"),
                            (1, "Inactive"),
                            (2, "Draft"),
                            (3, "Released"),
                            (4, "Approved Draft"),
                            (5, "Absent"),
                            (6, "Purchase Order"),
                            (7, "Suspend"),
                            (8, "On Hold"),
                            (9, "Hardwired"),
                            (10, "Loss"),
                            (11, "Freeze"),
                            (12, "For Adjustment"),
                            (13, "Distributor Order"),
                        ],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[(1, "Introducer"), (2, "Advisor"), (3, "Admin")],
                        default=2,
                        max_length=64,
                        verbose_name="Role",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Designation",
                    ),
                ),
                (
                    "official_email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Official Email",
                    ),
                ),
                (
                    "official_phone",
                    models.CharField(
                        blank=True,
                        max_length=24,
                        null=True,
                        verbose_name="Official Phone",
                    ),
                ),
                (
                    "permanent_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Permanent Address",
                    ),
                ),
                (
                    "present_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Present Address",
                    ),
                ),
                (
                    "dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[(1, "Male"), (2, "Female"), (3, "Other")],
                        default=1,
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "joining_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Joining Date"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Registration Number",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Degree"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active Status"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_users",
                        to="organization.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization User",
                "verbose_name_plural": "Organization Users",
                "unique_together": {("user", "organization")},
            },
        ),
    ]
