# Generated by Django 5.1.2 on 2024-11-07 12:17

import enumerify.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="status",
            field=enumerify.fields.SelectIntegerField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("DRAFT", "Draft"),
                    ("RELEASED", "Released"),
                    ("APPROVED_DRAFT", "Approved Draft"),
                    ("ABSENT", "Absent"),
                    ("PURCHASE_ORDER", "Purchase Order"),
                    ("SUSPEND", "Suspend"),
                    ("ON_HOLD", "On Hold"),
                    ("HARDWIRED", "Hardwired"),
                    ("LOSS", "Loss"),
                    ("FREEZE", "Freeze"),
                    ("FOR_ADJUSTMENT", "For Adjustment"),
                    ("DISTRIBUTOR_ORDER", "Distributor Order"),
                ],
                default="ACTIVE",
            ),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other")],
                default="MALE",
                max_length=10,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("INTRODUCER", "Introducer"),
                    ("ADVISOR", "Advisor"),
                    ("ADMIN", "Admin"),
                ],
                default="ADVISOR",
                max_length=64,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="status",
            field=enumerify.fields.SelectIntegerField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("DRAFT", "Draft"),
                    ("RELEASED", "Released"),
                    ("APPROVED_DRAFT", "Approved Draft"),
                    ("ABSENT", "Absent"),
                    ("PURCHASE_ORDER", "Purchase Order"),
                    ("SUSPEND", "Suspend"),
                    ("ON_HOLD", "On Hold"),
                    ("HARDWIRED", "Hardwired"),
                    ("LOSS", "Loss"),
                    ("FREEZE", "Freeze"),
                    ("FOR_ADJUSTMENT", "For Adjustment"),
                    ("DISTRIBUTOR_ORDER", "Distributor Order"),
                ],
                default="ACTIVE",
            ),
        ),
    ]
