# Generated by Django 5.1.2 on 2024-11-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_alter_organization_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationuser",
            name="is_active",
        ),
    ]
