# Generated by Django 5.1.2 on 2024-11-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_remove_organizationuser_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="status",
        ),
        migrations.RemoveField(
            model_name="organizationuser",
            name="status",
        ),
    ]
