# Generated by Django 5.1.2 on 2024-11-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0005_alter_organization_contact_person_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
    ]
