# Generated by Django 5.1.2 on 2024-11-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0006_organization_is_removed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="contact_person",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
