# Generated by Django 5.1.2 on 2024-11-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0007_alter_organization_contact_person"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizationuser",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Organization User",
                "verbose_name_plural": "Organization Users",
            },
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("INTRODUCER", "Introducer"),
                    ("ADVISOR", "Advisor"),
                    ("ADMIN", "Admin"),
                    ("LEAD", "Lead"),
                    ("CLIENT", "Client"),
                ],
                default="ADVISOR",
                max_length=64,
                verbose_name="Role",
            ),
        ),
    ]
