# Generated by Django 5.1.2 on 2024-11-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0008_alter_organizationuser_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ("-created_at",)},
        ),
    ]
