# Generated by Django 5.1.2 on 2024-12-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0009_alter_organization_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="organizationuser",
            options={
                "ordering": ["-created_at", "-updated_at"],
                "verbose_name": "Organization User",
                "verbose_name_plural": "Organization Users",
            },
        ),
    ]
