# Generated by Django 5.1.2 on 2024-12-30 10:23

import autoslug.fields
import common.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0011_alter_organizationuser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        allow_unicode=True,
                        always_update=True,
                        editable=False,
                        populate_from="name",
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "logo",
                    common.fields.TimestampThumbnailImageField(
                        blank=True, null=True, upload_to="network/logo"
                    ),
                ),
                (
                    "profile_image",
                    common.fields.TimestampThumbnailImageField(
                        blank=True, null=True, upload_to="network/profile"
                    ),
                ),
                (
                    "hero_image",
                    common.fields.TimestampThumbnailImageField(
                        blank=True, null=True, upload_to="network/hero"
                    ),
                ),
                ("primary_mobile", models.CharField(max_length=20)),
                (
                    "other_contact",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "contact_person_designation",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("license_no", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "license_image",
                    common.fields.TimestampThumbnailImageField(
                        blank=True, null=True, upload_to="network/license"
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="network",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization",
                to="organization.network",
                verbose_name="Network",
            ),
        ),
    ]
