# Generated by Django 5.1.2 on 2024-12-30 14:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0012_network_organization_network"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("INTRODUCER", "Introducer"),
                            ("ADVISOR", "Advisor"),
                            ("ADMIN", "Admin"),
                            ("LEAD", "Lead"),
                            ("CLIENT", "Client"),
                            ("JOINT_USER", "Joint User"),
                        ],
                        default="ADMIN",
                        max_length=64,
                        verbose_name="Role",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Designation",
                    ),
                ),
                (
                    "official_email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Official Email",
                    ),
                ),
                (
                    "official_phone",
                    models.CharField(
                        blank=True,
                        max_length=24,
                        null=True,
                        verbose_name="Official Phone",
                    ),
                ),
                (
                    "permanent_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Permanent Address",
                    ),
                ),
                (
                    "present_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Present Address",
                    ),
                ),
                (
                    "dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        default="MALE",
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "joining_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Joining Date"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Registration Number",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Degree"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_users",
                        to="organization.network",
                        verbose_name="Network",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Network User",
                "verbose_name_plural": "Network Users",
                "ordering": ["-created_at", "-updated_at"],
                "unique_together": {("user", "network")},
            },
        ),
    ]
