# Generated by Django 5.1.2 on 2025-05-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0013_networkuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("INTRODUCER", "Introducer"),
                    ("ADVISOR", "Advisor"),
                    ("ADMIN", "Admin"),
                    ("LEAD", "Lead"),
                    ("CLIENT", "Client"),
                    ("JOINT_USER", "Joint User"),
                    ("NETWORK_CEO", "Network CEO"),
                    ("NETWORK_COO", "Network COO"),
                    ("NETWORK_SYSTEM_DEVELOPER", "Network System Developer"),
                    ("NETWORK_COMPLIANCE_MANAGER", "Network Compliance Manager"),
                    ("NETWORK_COMPLIANCE_ASSISTANT", "Network Compliance Assistant"),
                    ("NETWORK_PRINCIPAL_ADVISER", "Network Principal Adviser"),
                    ("NETWORK_ADVISER", "Network Adviser"),
                    ("NETWORK_ADMIN", "Network Admin"),
                    ("NETWORK_SUPPORT", "Network Support Staff"),
                ],
                default="NETWORK_SUPPORT",
                max_length=64,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("INTRODUCER", "Introducer"),
                    ("ADVISOR", "Advisor"),
                    ("ADMIN", "Admin"),
                    ("LEAD", "Lead"),
                    ("CLIENT", "Client"),
                    ("JOINT_USER", "Joint User"),
                    ("ORGANIZATION_CEO", "Organization CEO"),
                    ("ORGANIZATION_COO", "Organization COO"),
                    ("ORGANIZATION_SYSTEM_DEVELOPER", "Organization System Developer"),
                    (
                        "ORGANIZATION_COMPLIANCE_MANAGER",
                        "Organization Compliance Manager",
                    ),
                    (
                        "ORGANIZATION_COMPLIANCE_ASSISTANT",
                        "Organization Compliance Assistant",
                    ),
                    (
                        "ORGANIZATION_PRINCIPAL_ADVISER",
                        "Organization Principal Adviser",
                    ),
                    ("ORGANIZATION_ADVISER", "Organization Adviser"),
                    ("ORGANIZATION_ADMIN", "Organization Admin"),
                    ("ORGANIZATION_SUPPORT", "Organization Support Staff"),
                ],
                default="ORGANIZATION_SUPPORT",
                max_length=64,
                verbose_name="Role",
            ),
        ),
    ]
