# Generated by Django 5.1.2 on 2024-12-03 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0010_alter_organization_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "product_category",
                    models.CharField(
                        choices=[
                            ("MORTGAGES", "Mortgages"),
                            ("PROTECTION", "Protection"),
                            ("GENERAL_INSURANCE", "General Insurance"),
                        ],
                        db_index=True,
                        default="MORTGAGES",
                        max_length=50,
                    ),
                ),
                (
                    "applicant_type",
                    models.CharField(
                        choices=[("SINGLE", "Single"), ("JOINT", "Joint")],
                        db_index=True,
                        default="SINGLE",
                        max_length=50,
                    ),
                ),
                (
                    "case_status",
                    models.CharField(
                        choices=[
                            ("NEW_LEAD", "New Lead"),
                            ("CALL_BACK", "Call Back"),
                            ("MEETING", "Meeting"),
                        ],
                        db_index=True,
                        default="NEW_LEAD",
                        max_length=50,
                    ),
                ),
                (
                    "case_stage",
                    models.CharField(
                        choices=[
                            ("INQUIRY", "Inquiry"),
                            ("FACT_FIND", "Fact Find"),
                            (
                                "RESEARCH_COMPLIANCE_CHECK",
                                "Research and Compliance Check",
                            ),
                            ("DECISION_IN_PRINCIPLE", "Decision in Principle"),
                            ("FULL_MORTGAGE_APPLICATION", "Full Mortgage Application"),
                            ("OFFER_FROM_BANK", "Offer From Bank"),
                            ("LEGAL", "Legal"),
                            ("COMPLETION", "Completion"),
                            ("FUTURE_OPPORTUNITY", "Future Opportunity"),
                            ("NOT_PROCEED", "Not Proceed"),
                        ],
                        db_index=True,
                        default="INQUIRY",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "is_removed",
                    models.BooleanField(blank=True, db_index=True, default=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
    ]
