# Generated by Django 5.1.2 on 2024-12-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="product_category",
            new_name="case_category",
        ),
    ]
