# Generated by Django 5.1.2 on 2024-12-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0002_rename_product_category_case_case_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_category",
            field=models.CharField(
                choices=[
                    ("MORTGAGE", "Mortgage"),
                    ("PROTECTION", "Protection"),
                    ("GENERAL_INSURANCE", "General Insurance"),
                ],
                db_index=True,
                default="MORTGAGE",
                max_length=50,
            ),
        ),
    ]
