# Generated by Django 5.1.2 on 2024-12-12 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0006_files_file_owner_files_file_type_files_is_deleted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="files",
            old_name="is_deleted",
            new_name="is_removed",
        ),
        migrations.AddField(
            model_name="jointuser",
            name="relationship",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="files",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("COMPLIANCE_DOCUMENTS", "Compliance Documents"),
                    ("FACT_FINDS", "Fact Finds"),
                    ("IDS", "IDs"),
                    ("PROOF_OF_ADDRESS", "Proof of Address"),
                    ("INCOME_DOCUMENTS", "Income Documents"),
                    ("BANK_STATEMENTS", "Bank Statements"),
                    (
                        "PROOF_OF_DEPOSIT_BANK_STATEMENTS",
                        "Proof of Deposit - Bank Statements",
                    ),
                    ("DONOR_DOCUMENTS", "Donor Documents"),
                    ("CREDIT_REPORT", "Credit Report"),
                    ("RESEARCH_DOCUMENTS", "Research Documents"),
                    ("LENDERS_KFI", "Lender's KFI"),
                    ("LENDERS_DIP", "Lender's DIP"),
                    (
                        "LENDERS_FULL_MORTGAGE_APPLICATION",
                        "Lender's Full Mortgage Application",
                    ),
                    ("LENDERS_OFFER", "Lender's Offer"),
                    ("SUITABILITY_LETTER", "Suitability Letter"),
                    ("GENERAL_INSURANCE_DOCUMENTS", "General Insurance Documents"),
                    ("PROTECTION_DOCUMENTS", "Protection Documents"),
                    ("AML_AND_SANCTIONS_SEARCH", "AML and Sanctions Search"),
                    ("OTHERS", "Others"),
                ],
                db_index=True,
                default="IDS",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "Upcoming Meeting"),
                            ("PREVIOUS", "Previous Meeting"),
                        ],
                        db_index=True,
                        default="UPCOMING",
                        max_length=50,
                    ),
                ),
                (
                    "meeting_status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Canceled"),
                            ("ON_HOLD", "On Hold"),
                            ("SUCCESS", "Success"),
                        ],
                        db_index=True,
                        default="CONFIRMED",
                        max_length=50,
                    ),
                ),
                (
                    "special_notes",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("meeting_link", models.URLField(blank=True, null=True)),
                ("meeting_date", models.DateField(blank=True, null=True)),
                ("meeting_time", models.TimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="case.case",
                        verbose_name="Related Case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
    ]
