# Generated by Django 5.1.2 on 2024-12-12 11:39

import case.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0007_rename_is_deleted_files_is_removed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Upload the file",
                upload_to=case.utils.upload_to_case_files,
                verbose_name="File",
            ),
        ),
    ]
