# Generated by Django 5.1.2 on 2024-12-13 10:30

import case.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0008_alter_files_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="file",
            field=models.FileField(
                help_text="Upload the file",
                upload_to=case.utils.upload_to_case_files,
                verbose_name="File",
            ),
        ),
    ]
