# Generated by Django 5.1.2 on 2024-12-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0009_alter_files_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="jointuser",
            name="is_removed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="meeting",
            name="is_removed",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
