# Generated by Django 5.1.2 on 2025-02-06 05:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0010_jointuser_is_removed_meeting_is_removed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("BUSINESS_LOAN", "Business Loan"),
                            ("BUY_TO_LET", "Buy to Let Mortgage"),
                            ("COMMERCIAL_MORTGAGE", "Commercial Mortgage"),
                            ("HMO_MORTGAGE", "HMO Mortgage"),
                            ("RESIDENTIAL_MORTGAGE", "Residential Mortgage"),
                            ("SECOND_CHARGE_MORTGAGE", "Second Charge Mortgage"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "mortgage_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PURCHASE", "Purchase"),
                            ("REMORTGAGE", "Remortgage"),
                            ("SECURED_LOAN", "Secured Loan"),
                            ("FURTHER_ADVANCE", "Further Advance"),
                            ("PRODUCT_TRANSFER", "Product Transfer"),
                            ("OTHER", "Other"),
                            ("UNSECURED", "Unsecured"),
                            ("INVOICE_DISCOUNTING", "Invoice Discounting"),
                            ("ASSET_FINANCE", "Asset Finance"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "loan_purpose",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PURCHASE", "Purchase"),
                            ("LIKE_FOR_LIKE_REMORTGAGE", "Like for Like Remortgage"),
                            ("BUSINESS_PURPOSES", "Business Purposes"),
                            ("DEBT_CONSOLIDATION", "Debt Consolidation"),
                            ("DIVORCE_SETTLEMENT", "Divorce Settlement"),
                            ("HOLIDAYS_CARS", "Holidays/Cars"),
                            ("HOME_IMPROVEMENTS", "Home Improvements"),
                            ("OTHER_PROPERTY_PURCHASE", "Other Property Purchase"),
                            ("SCHOOL_FEES", "School Fees"),
                            ("RATE_SWITCH", "Rate Switch (switch to better rate)"),
                            ("TAX_BILL", "Tax Bill"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "lender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACCORD_MORTGAGES", "Accord Mortgages"),
                            ("AHLI_UNITED_BANK", "Ahli United Bank"),
                            ("AL_RAYAN_BANK", "Al Rayan Bank"),
                            ("ALDERMORE_MORTGAGES", "Aldermore Mortgages"),
                            ("AMICUS_PLC", "Amicus PLC"),
                            ("ASSETZ_CAPITAL", "Assetz Capital"),
                            ("ATOM_BANK", "Atom Bank"),
                            ("AVIVA_EQUITY_RELEASE", "Aviva Equity Release"),
                            ("AXIS_BANK", "Axis Bank"),
                            ("BANK_AND_CLIENTS_PLC", "Bank & Clients PLC"),
                            ("BANK_OF_CHINA", "Bank of China"),
                            ("BANK_OF_CYPRUS_UK", "Bank of Cyprus UK"),
                            ("BANK_OF_IRELAND", "Bank of Ireland"),
                            ("BARCLAYS", "Barclays"),
                            ("BARCLAYS_COMMERCIAL", "Barclays Commercial"),
                            ("BATH_BUILDING_SOCIETY", "Bath Building Society"),
                            ("BEVERLEY_BUILDING_SOCIETY", "Beverley Building Society"),
                            ("BLUESTONE_MORTGAGES", "Bluestone Mortgages"),
                            ("BLUEZEST", "BlueZest"),
                            ("BM_SOLUTIONS", "BM Solutions"),
                            ("BOOST_CAPITAL", "Boost Capital"),
                            (
                                "BRIDGEWATER_EQUITY_RELEASE",
                                "Bridgewater Equity Release",
                            ),
                            (
                                "BUCKINGHAMSHIRE_BUILDING_SOCIETY",
                                "Buckinghamshire Building Society",
                            ),
                            (
                                "CAMBRIDGE_AND_COUNTIES_BANK",
                                "Cambridge and Counties Bank",
                            ),
                            (
                                "CAMBRIDGE_BUILDING_SOCIETY",
                                "Cambridge Building Society",
                            ),
                            ("CENTRAL_TRUST", "Central Trust"),
                            ("CHARTERBANK", "Charterbank"),
                            ("CHL_MORTGAGES", "CHL Mortgages"),
                            (
                                "CHORLEY_DISTRICT_BUILDING_SOCIETY",
                                "Chorley & District Building Society",
                            ),
                            ("CLEARLY_LOANS", "Clearly Loans"),
                            ("COUTTS", "Coutts"),
                            ("COVENTRY_BUILDING_SOCIETY", "Coventry Building Society"),
                            ("CROWN_EQUITY_RELEASE", "Crown Equity Release"),
                            (
                                "CUMBERLAND_BUILDING_SOCIETY",
                                "Cumberland Building Society",
                            ),
                            ("DANSKE_BANK", "Danske Bank"),
                            (
                                "DARLINGTON_BUILDING_SOCIETY",
                                "Darlington Building Society",
                            ),
                            ("DIGITAL_MORTGAGES", "Digital Mortgages"),
                            ("DUDLEY_BUILDING_SOCIETY", "Dudley Building Society"),
                            (
                                "EARL_SHILTON_BUILDING_SOCIETY",
                                "Earl Shilton Building Society",
                            ),
                            ("ECOLOGY_BUILDING_SOCIETY", "Ecology Building Society"),
                            ("EQUIFINANCE", "Equifinance"),
                            ("FAMILY_BUILDING_SOCIETY", "Family Building Society"),
                            ("FINSEC", "FinSec"),
                            ("FIRST_TRUST_BANK", "First Trust Bank"),
                            ("FLEET_MORTGAGES", "Fleet Mortgages"),
                            ("FOUNDATION_HOME_LOANS", "Foundation Home Loans"),
                            ("FURNESS_BUILDING_SOCIETY", "Furness Building Society"),
                            ("GATEHOUSE_BANK", "Gatehouse Bank"),
                            ("GENERATION_HOME", "Generation Home"),
                            ("GODIVA_MORTGAGES", "Godiva Mortgages"),
                            ("HALIFAX", "Halifax"),
                            ("HAMPSHIRE_TRUST_BANK", "Hampshire Trust Bank"),
                            ("HANDELSBANKEN", "Handelsbanken"),
                            (
                                "HANLEY_ECONOMIC_BUILDING_SOCIETY",
                                "Hanley Economic Building Society",
                            ),
                            ("HARPDEN_BUILDING_SOCIETY", "Harpenden Building Society"),
                            ("HSBC", "HSBC"),
                            ("ICICI_BANK", "ICICI Bank"),
                            ("INTERBAY_COMMERCIAL", "Interbay Commercial"),
                            ("INVESTEC", "Investec"),
                            ("IPSWICH_BUILDING_SOCIETY", "Ipswich Building Society"),
                            ("JUST_RETIREMENT_SOLUTIONS", "Just Retirement Solutions"),
                            ("KENSINGTON_MORTGAGES", "Kensington Mortgages"),
                            ("KENT_RELIANCE", "Kent Reliance"),
                            ("KEYSTONE_PROPERTY_FINANCE", "Keystone Property Finance"),
                            ("LEEDS_BUILDING_SOCIETY", "Leeds Building Society"),
                            (
                                "LEEK_UNITED_BUILDING_SOCIETY",
                                "Leek United Building Society",
                            ),
                            ("METRO_BANK", "Metro Bank"),
                            (
                                "MONMOUTHSHIRE_BUILDING_SOCIETY",
                                "Monmouthshire Building Society",
                            ),
                            ("NATIONWIDE", "Nationwide"),
                            ("NATWEST", "NatWest"),
                            (
                                "NOTTINGHAM_BUILDING_SOCIETY",
                                "Nottingham Building Society",
                            ),
                            ("PARAGON_MORTGAGES", "Paragon Mortgages"),
                            ("PEPPER_MONEY", "Pepper Money"),
                            ("POST_OFFICE_MORTGAGES", "Post Office Mortgages"),
                            (
                                "PRINCIPALITY_BUILDING_SOCIETY",
                                "Principality Building Society",
                            ),
                            ("SANTANDER", "Santander"),
                            ("SKIPTON_BUILDING_SOCIETY", "Skipton Building Society"),
                            ("TSB", "TSB"),
                            ("ULSTER_BANK", "Ulster Bank"),
                            ("UNKNOWN", "Unknown"),
                            ("UNKNOWN_DEFAULT", "Unknown (Default)"),
                            ("VIDA_HOMELOANS", "Vida Homeloans"),
                            (
                                "WEST_BROMWICH_BUILDING_SOCIETY",
                                "West Bromwich Building Society",
                            ),
                            ("WEST_ONE_LOANS", "West One Loans"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "lenders_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "borrower_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HOMEMOVER", "Homemover"),
                            ("FIRST_TIME_BUYER", "First Time Buyer"),
                            ("RE_MORTGAGE", "Re-Mortgage"),
                            ("CAPITAL_RAISE", "Capital Raise"),
                            ("HELP_TO_BUY", "Help to Buy"),
                            ("SHARED_OWNERSHIP", "Shared Ownership"),
                            ("RIGHT_TO_BUY", "Right to Buy"),
                            ("LATER_LIFE_LENDING", "Later Life Lending"),
                            ("EQUITY_RELEASE", "Equity Release"),
                            ("BUY_TO_LET", "Buy to Let"),
                            ("LET_TO_BUY", "Let to Buy"),
                            ("FIRST_TIME_LANDLORD", "First Time Landlord"),
                            ("PORTFOLIO_LANDLORD", "Portfolio Landlord"),
                            ("SHARED_EQUITY", "Shared Equity"),
                            ("ISLAMIC_MORTGAGE", "Islamic Mortgage"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "repayment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CAPITAL_AND_INTEREST", "Capital and Interest"),
                            ("INTEREST_ONLY", "Interest Only"),
                            ("PART_AND_PART", "Part And Part"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "repayment_vehicle",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ENDOWMENT", "Endowment"),
                            (
                                "INDIVIDUAL_SAVINGS_ACCOUNT",
                                "Individual Savings Account",
                            ),
                            ("PENSION", "Pension"),
                            (
                                "SALE_OF_MORTGAGED_PROPERTY",
                                "Sale of Mortgaged Property",
                            ),
                            ("SALE_OF_OTHER_PROPERTY", "Sale of Other Property"),
                            ("INHERITANCE", "Inheritance"),
                            (
                                "MORTGAGE_LINKED_INVESTMENT",
                                "Mortgage-Linked Investment",
                            ),
                            (
                                "REVERT_TO_CAPITAL_REPAYMENT",
                                "Revert to Capital Repayment",
                            ),
                            (
                                "SALE_OF_NON_PROPERTY_ASSETS",
                                "Sale of non-Property Assets",
                            ),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "interest_rate_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FIXED", "Fixed"),
                            ("VARIABLE", "Variable"),
                            ("TRACKER", "Tracker"),
                            ("LIBOR_LINKED", "Libor Linked"),
                            ("DISCOUNT", "Discount"),
                            ("CAPPED", "Capped"),
                            ("ALL", "All"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "product_term",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ONE_YEAR", "1 Year"),
                            ("TWO_YEARS", "2 Years"),
                            ("THREE_YEARS", "3 Years"),
                            ("FOUR_YEARS", "4 Years"),
                            ("FIVE_PLUS_YEARS", "5+ Years"),
                            ("FULL_TERM", "Full Term"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "estimated_value",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "ltv",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("term_years", models.PositiveIntegerField(default=0)),
                ("term_months", models.PositiveIntegerField(default=0)),
                (
                    "deposit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "deposit_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "interest_only_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "advice_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADVISING", "Advising"),
                            ("EXECUTION_ONLY", "Execution Only"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("dip_accept_date", models.DateField(blank=True, null=True)),
                ("dip_expiry_date", models.DateField(blank=True, null=True)),
                ("expected_completion_date", models.DateField(blank=True, null=True)),
                ("product_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "introduction_type",
                    models.CharField(
                        blank=True,
                        choices=[("DIRECT", "Direct"), ("RDI", "RDI")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("introducer", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "introducer_payment_terms",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NOT_APPLICABLE", "Not Applicable"),
                            ("ON_APPLICATION", "On Application"),
                            ("ON_OFFER", "On Offer"),
                            ("ON_COMPLETION", "On Completion"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "introducer_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "lead_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FACEBOOK", "Facebook"),
                            ("ESTATE_AGENTS", "Estate Agents"),
                            ("TV3", "TV3"),
                            ("FAMILY", "Family"),
                            ("FRIENDS", "Friends"),
                            ("REFERRALS", "Referrals"),
                            ("WEBSITE", "Website"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "sale_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("FACE_TO_FACE", "Face to Face"),
                            ("TELEPHONE", "Telephone"),
                            ("INTERNET", "Internet"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "reasons_for_capital_raising",
                    models.TextField(blank=True, null=True),
                ),
                ("case_summary", models.TextField(blank=True, null=True)),
                ("accepted_or_declined_by_lender", models.BooleanField(default=False)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_details",
                        to="case.case",
                        verbose_name="Related Case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
