# Generated by Django 5.1.2 on 2025-02-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "case",
            "0012_rename_deposit_amount_loandetails_current_monthly_payment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="loandetails",
            name="deposit_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="deposit_source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="purchase_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="loandetails",
            name="application_type",
            field=models.CharField(
                choices=[
                    ("SELECT_APPLICATION_TYPE", "Select Application Type"),
                    ("BUSINESS_LOAN", "Business Loan"),
                    ("BUY_TO_LET", "Buy to Let Mortgage"),
                    ("COMMERCIAL_MORTGAGE", "Commercial Mortgage"),
                    ("HMO_MORTGAGE", "HMO Mortgage"),
                    ("RESIDENTIAL_MORTGAGE", "Residential Mortgage"),
                    ("SECOND_CHARGE_MORTGAGE", "Second Charge Mortgage"),
                ],
                default="SELECT_APPLICATION_TYPE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="loandetails",
            name="estimated_value",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="loandetails",
            name="loan_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="loandetails",
            name="property_valuation",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
