# Generated by Django 5.1.2 on 2025-02-18 08:33

import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0013_loandetails_deposit_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "company_registration_number",
                    models.CharField(max_length=50, unique=True),
                ),
                ("date_of_incorporation", models.DateField(blank=True, null=True)),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("PRIVATE_LIMITED", "Private Limited Company"),
                            ("PUBLIC_LIMITED", "Public Limited Company"),
                            ("SOLE_TRADER", "Sole Trader"),
                            ("PARTNERSHIP", "Partnership"),
                            (
                                "LIMITED_LIABILITY_PARTNERSHIP",
                                "Limited Liability Partnership",
                            ),
                            ("OTHER", "Other"),
                        ],
                        default="PRIVATE_LIMITED",
                        max_length=50,
                    ),
                ),
                (
                    "trade_business_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sic_code", models.CharField(blank=True, max_length=255, null=True)),
                ("is_spv", models.BooleanField(default=False)),
                ("postcode", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "house_number_or_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ApplicantDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("is_company_application", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        choices=[("MR", "Mr"), ("MRS", "Mrs"), ("MS", "Ms")],
                        default="MR",
                        max_length=10,
                    ),
                ),
                (
                    "maiden_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("anticipated_retirement_age", models.PositiveIntegerField(default=0)),
                ("state_retirement_age", models.PositiveIntegerField(default=0)),
                ("is_smoker", models.BooleanField(default=False)),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")],
                        default="MALE",
                        max_length=6,
                    ),
                ),
                ("nationality", django_countries.fields.CountryField(max_length=2)),
                ("dual_nationality", models.BooleanField(default=False)),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("SEPARATED", "Separated"),
                            ("WIDOW", "Widow"),
                            ("WIDOWER", "Widower"),
                            ("CO_HABITING", "Co-Habiting"),
                            ("CIVIL_PARTNER", "Civil Partner"),
                            ("RELIGIOUSLY_MARRIED", "Religiously Married"),
                        ],
                        default="SINGLE",
                        max_length=30,
                    ),
                ),
                ("ni_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "country_of_birth",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                ("home_phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "mobile_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("work_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "marketing_preferences",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("EMAIL", "Email"),
                            ("TELEPHONE", "Telephone"),
                            ("SMS", "SMS"),
                            ("POST", "Post"),
                            ("NO_COMMUNICATION", "No Communication"),
                        ],
                        max_length=100,
                    ),
                ),
                ("has_dependants", models.BooleanField(default=False)),
                ("number_of_dependants", models.PositiveIntegerField(default=0)),
                ("date_of_arrival_uk", models.DateField(blank=True, null=True)),
                ("indefinite_right_to_reside", models.BooleanField(default=False)),
                (
                    "visa_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("visa_expiry_date", models.DateField(blank=True, null=True)),
                ("postcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "house_number_or_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("time_at_address_years", models.PositiveIntegerField(default=0)),
                ("time_at_address_months", models.PositiveIntegerField(default=0)),
                (
                    "residential_status",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("RENTING_PRIVATE", "Renting - private"),
                            ("RENTING_LOCAL_AUTHORITY", "Renting - Local Authority"),
                            ("TIED_ACCOMMODATION", "Tied Accommodation"),
                            ("LIVING_WITH_PARENTS", "Living with Parents"),
                            (
                                "LIVING_WITH_FRIENDS_FAMILY",
                                "Living with Friends/Family",
                            ),
                        ],
                        default="OWNER",
                        max_length=50,
                    ),
                ),
                (
                    "current_mortgage_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "property_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "owner_monthly_payment",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("lender", models.CharField(blank=True, max_length=100, null=True)),
                ("mortgage_start_date", models.DateField(blank=True, null=True)),
                (
                    "mortgage_type",
                    models.CharField(
                        choices=[
                            ("SECURED_LOAN", "Secured Loan (Applicant Commitments)"),
                            ("SECOND_HOME", "Second Home (Applicant Commitments)"),
                            ("HOLIDAY_HOME", "Holiday Home (Applicant Commitments)"),
                            ("BUY_TO_LET", "Buy to Let (Applicant Mortgage Details)"),
                            ("HOLIDAY_LET", "Holiday Let (Applicant Mortgage Details)"),
                            (
                                "COMMERCIAL_INVESTMENT",
                                "Commercial Investment (Applicant Mortgage Details)",
                            ),
                        ],
                        default="SECURED_LOAN",
                        max_length=100,
                    ),
                ),
                (
                    "current_interest_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("remaining_term", models.PositiveIntegerField(default=0)),
                (
                    "repayment_type",
                    models.CharField(
                        choices=[
                            ("CAPITAL_INTEREST", "Capital and Interest"),
                            ("INTEREST_ONLY", "Interest Only"),
                            ("PART_AND_PART", "Part And Part"),
                            ("SERVICED", "Serviced"),
                            ("ROLLED_UP", "Rolled Up"),
                            ("RETAINED", "Retained"),
                            ("OTHER", "Other"),
                        ],
                        default="CAPITAL_INTEREST",
                        max_length=50,
                    ),
                ),
                (
                    "current_interest_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed"),
                            ("VARIABLE", "Variable"),
                            ("TRACKER", "Tracker"),
                            ("DISCOUNT", "Discount"),
                            ("CAPPED", "Capped"),
                            ("SVR", "SVR"),
                            ("OFFSET", "Offset"),
                            ("LIFETIME", "Lifetime"),
                            ("OTHER", "Other"),
                        ],
                        default="FIXED",
                        max_length=50,
                    ),
                ),
                ("early_repayment_charge_applies", models.BooleanField(default=False)),
                ("erc_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "erc_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("erc_being_paid", models.BooleanField(default=False)),
                (
                    "mortgage_account_number",
                    models.CharField(max_length=50, unique=True),
                ),
                ("being_redeemed", models.BooleanField(default=False)),
                ("is_mortgage_portable", models.BooleanField(default=False)),
                ("is_mortgage_being_ported", models.BooleanField(default=False)),
                (
                    "mortgage_not_to_complete_until_erc_ended",
                    models.CharField(
                        blank=True,
                        choices=[("NA", "N/A"), ("YES", "Yes"), ("NO", "No")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("mortgage_charter_scheme", models.BooleanField(default=False)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("HOUSE", "House"),
                            ("FLAT", "Flat"),
                            ("MAISONETTE", "Maisonette"),
                            ("BUNGALOW", "Bungalow"),
                            ("WAREHOUSE", "Warehouse"),
                            ("LAND", "Land"),
                            ("COMMERCIAL", "Commercial"),
                            ("SEMI_COMMERCIAL", "Semi-Commercial"),
                            ("MULTI_UNIT_BLOCK", "Multi-Unit Block (MUB)"),
                            ("HMO", "HMO"),
                        ],
                        default="HOUSE",
                        max_length=50,
                    ),
                ),
                ("bedrooms", models.PositiveIntegerField(default=0)),
                (
                    "tenure",
                    models.CharField(
                        choices=[
                            ("FREEHOLD", "Freehold"),
                            ("LEASEHOLD", "Leasehold"),
                            ("COMMONHOLD", "Commonhold"),
                            ("FEUDAL", "Feudal"),
                        ],
                        default="FREEHOLD",
                        max_length=50,
                    ),
                ),
                ("year_built", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant_details",
                        to="case.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant_company",
                        to="case.companyinfo",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dependant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "applicant_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependants",
                        to="case.applicantdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DirectorShareholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "percentage_share",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DIRECTOR", "Director"),
                            ("SHAREHOLDER", "Share Holder"),
                            ("BOTH", "Both"),
                        ],
                        default="DIRECTOR",
                        max_length=50,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directors_shareholders",
                        to="case.companyinfo",
                    ),
                ),
            ],
        ),
    ]
