# Generated by Django 5.1.2 on 2025-02-18 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0015_alter_applicantdetails_mortgage_account_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicantdetails",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicant_details",
                to="case.case",
            ),
        ),
    ]
