# Generated by Django 5.1.2 on 2025-02-19 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0018_remove_applicantdetails_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinfo",
            name="applicant_details",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to="case.applicantdetails",
            ),
        ),
    ]
