# Generated by Django 5.1.2 on 2025-02-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0019_alter_companyinfo_applicant_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicantdetails",
            name="mortgage_account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
