# Generated by Django 5.1.2 on 2025-02-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0021_applicantdetails_dual_nationality_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinfo",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("PRIVATE_LIMITED", "Private Limited Company"),
                    ("PUBLIC_LIMITED", "Public Limited Company"),
                    ("SOLE_TRADER", "Sole Trader"),
                    ("PARTNERSHIP", "Partnership"),
                    ("LIMITED_LIABILITY_PARTNERSHIP", "Limited Liability Partnership"),
                    ("OTHER", "Other"),
                ],
                default="PRIVATE_LIMITED",
                max_length=50,
            ),
        ),
    ]
