# Generated by Django 5.1.2 on 2025-02-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0022_alter_companyinfo_company_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmploymentDetails",
        ),
    ]
