# Generated by Django 5.1.2 on 2025-02-24 09:04

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0023_delete_employmentdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantdetails",
            name="is_dual_nationality",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="applicantdetails",
            name="dual_nationality",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicantdetails",
            name="title",
            field=models.CharField(
                choices=[("MR", "Mr"), ("MRS", "Mrs"), ("MS", "Ms"), ("MISS", "Miss")],
                default="MR",
                max_length=10,
            ),
        ),
    ]
