# Generated by Django 5.1.2 on 2025-02-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0025_employmentdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employmentdetails",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("EMPLOYED", "Employed"),
                    ("SELF_EMPLOYED", "Self Employed"),
                    ("RETIRED", "Retired"),
                    ("OTHER", "Other"),
                    ("UNEMPLOYED", "Unemployed"),
                    ("HOUSEPERSON", "Houseperson"),
                    ("CONTRACTOR", "Contractor"),
                ],
                default="EMPLOYED",
                max_length=50,
            ),
        ),
    ]
