# Generated by Django 5.1.2 on 2025-02-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0026_alter_employmentdetails_employment_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employmentdetails",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterUniqueTogether(
            name="employmentdetails",
            unique_together=set(),
        ),
    ]
