# Generated by Django 5.1.2 on 2025-03-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0031_alter_paydayloan_options_remove_adverse_bankrupt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="debtmanagementplan",
            name="user",
        ),
        migrations.RemoveField(
            model_name="individualvoluntary",
            name="user",
        ),
        migrations.RemoveField(
            model_name="paydayloan",
            name="user",
        ),
        migrations.RemoveField(
            model_name="paymentcommitment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="propertyrepossessed",
            name="user",
        ),
        migrations.RemoveField(
            model_name="registerloan",
            name="user",
        ),
    ]
