# Generated by Django 5.1.2 on 2025-03-06 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0032_remove_debtmanagementplan_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankrupt",
            name="adverse",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bankrupt",
                to="case.adverse",
            ),
            preserve_default=False,
        ),
    ]
