# Generated by Django 5.1.2 on 2025-03-10 06:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0036_property"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitorAccountant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("Accountant", "Accountant"),
                            ("Solicitor", "Solicitor"),
                        ],
                        default="Accountant",
                        max_length=255,
                    ),
                ),
                ("sra_number", models.CharField(blank=True, max_length=255, null=True)),
                ("postcode", models.CharField(max_length=255)),
                (
                    "building_name_or_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("county", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fax_number", models.CharField(max_length=255)),
                ("dx_number", models.CharField(max_length=255)),
                ("contact_name", models.CharField(max_length=255)),
                (
                    "email_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "number_of_partners_in_firm",
                    models.IntegerField(blank=True, null=True),
                ),
                ("qualifications", models.CharField(max_length=255)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitor_accountant",
                        to="case.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
    ]
