# Generated by Django 5.1.2 on 2025-03-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0037_solicitoraccountant"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitoraccountant",
            name="name",
            field=models.CharField(default="aaa", max_length=255),
            preserve_default=False,
        ),
    ]
