# Generated by Django 5.1.2 on 2025-03-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0039_existingprotection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="existingprotection",
            name="cancelled_lapsed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="existingprotection",
            name="date_policy_started",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="existingprotection",
            name="person_assured",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="existingprotection",
            name="policy_provider",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="existingprotection",
            name="premium",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="existingprotection",
            name="remaining_policy_term",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="existingprotection",
            name="renewal_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
