# Generated by Django 5.1.2 on 2025-03-10 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0040_alter_existingprotection_cancelled_lapsed_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "note_task",
                    models.CharField(
                        choices=[("NOTE", "Note"), ("TASK", "Task")],
                        default="NOTE",
                        max_length=255,
                    ),
                ),
                ("note_visible_to_introducer", models.BooleanField(default=False)),
                ("note_visible_to_client", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNCATEGORISED", "Uncategorised"),
                            ("EMAIL_CORRESPONDENCE", "Email Correspondence"),
                            ("TELEPHONE_CONVERSATION", "Telephone Conversation"),
                            ("LENDER_CORRESPONDENCE", "Lender Correspondence"),
                            ("SOLICITOR_CORRESPONDENCE", "Solicitor Correspondence"),
                            ("COMPLIANCE_CORRESPONDENCE", "Compliance Correspondence"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "task_priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("assigned_to", models.IntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
    ]
