# Generated by Django 5.1.2 on 2025-03-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0040_alter_existingprotection_cancelled_lapsed_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="existingprotection",
            name="in_trust",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NA", "N/A"),
                    ("YES", "Yes"),
                    ("NO", "No"),
                    ("CLIENT_TO_ASCERTAIN", "Client To Ascertain"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentcommitment",
            name="commitment_type",
            field=models.CharField(
                choices=[
                    ("CREDIT_CARD", "Credit Card"),
                    ("STORE_CARD", "Store Card"),
                    ("LOAN", "Loan"),
                    ("HP", "HP"),
                    ("OVERDRAFT", "Overdraft"),
                    ("STUDENT_LOAN", "Student Loan"),
                    ("MAINTENANCE", "Maintenance"),
                    ("LEASE", "Lease"),
                    ("UNSECURED", "Unsecured"),
                    ("MORTGAGE_RENT", "Mortgage/Rent"),
                    ("PUBLIC_UTILITY", "Public Utility"),
                    ("COMMUNICATIONS", "Communications"),
                    ("INSURANCE", "Insurance"),
                    ("SECURED", "Secured"),
                    ("PCP", "PCP"),
                    ("MAIL_ORDER", "Mail Order"),
                    ("CHILDCARE", "Childcare"),
                    ("CAR_FINANCE", "Car Finance"),
                    ("BUY_NOW_PAY_LATER", "Buy Now Pay Later (BNPL)"),
                    ("CREDIT_COMMITMENT", "Credit Commitment"),
                    ("DMP", "DMP"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="epc_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="rate_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("FIXED", "Fixed"),
                    ("VARIABLE", "Variable"),
                    ("TRACKER", "Tracker"),
                    ("LIBOR_LINKED", "Libor Linked"),
                    ("DISCOUNT", "Discount"),
                    ("CAPPED", "Capped"),
                    ("ALL", "All"),
                    ("SVR", "SVR"),
                    ("OFFSET", "Offset"),
                    ("LIFETIME", "Lifetime"),
                    ("OTHER", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="solicitoraccountant",
            name="user_type",
            field=models.CharField(
                choices=[("ACCOUNTANT", "Accountant"), ("SOLICITOR", "Solicitor")],
                default="ACCOUNTANT",
                max_length=255,
            ),
        ),
    ]
