# Generated by Django 5.1.2 on 2025-03-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0041_alter_existingprotection_in_trust_and_more"),
        ("case", "0042_existingprotection_case_notes_case"),
    ]

    operations = []
