# Generated by Django 5.1.2 on 2025-03-11 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0043_merge_20250311_0606"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("product_description", models.TextField()),
                ("initial_rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "initial_rate_type",
                    models.CharField(
                        choices=[
                            (
                                "PLEASE_SELECT_A_INITIAL_RATE_TYPE",
                                "Please Select A Initial Rate Type",
                            ),
                            ("FIXED", "Fixed"),
                            ("VARIABLE", "Variable"),
                            ("TRACKER", "Tracker"),
                            ("DISCOUNTED", "Discounted"),
                            ("ALL", "All"),
                        ],
                        default="PLEASE_SELECT_A_INITIAL_RATE_TYPE",
                        max_length=255,
                    ),
                ),
                (
                    "initial_rate_period_type",
                    models.CharField(
                        choices=[
                            (
                                "PLEASE_SELECT_A_INITIAL_RATE_PERIOD_TYPE",
                                "Please Select A Initial Rate Period Type",
                            ),
                            ("MONTHS", "Months"),
                            ("FIXED_DATE", "Fixed Date"),
                            ("END_OF_MORTGAGE_TERM", "End of Mortgage Term"),
                        ],
                        default="PLEASE_SELECT_A_INITIAL_RATE_PERIOD_TYPE",
                        max_length=255,
                    ),
                ),
                (
                    "reversion_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "initial_rate_period",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("initial_rate_date_period", models.DateField(blank=True, null=True)),
                (
                    "max_ltv",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "annual_percentage_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "product_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "PLEASE_SELECT_A_PRODUCT_CLASS",
                                "please Select A Product Class",
                            ),
                            ("BTL", "BTL"),
                            ("SECURED", "Secured"),
                            ("RESIDENTIAL", "Residential"),
                            ("BRIDGING", "Bridge"),
                            ("COMMERCIAL", "Commercial"),
                            ("LET_TO_BUY", "Let To Buy"),
                        ],
                        default="PLEASE_SELECT_A_PRODUCT_CLASS",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "early_repayment_charge",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "early_repayment_charge_end_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "initial_monthly_payment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "initial_monthly_payment_including_fees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "monthly_payment_after_initial_Period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "true_cost_over_initial_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "true_cost_over_term",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "true_cost_without_fees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "loan_required_including_fees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "arrangement_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "arrangement_fee_added_to_loan",
                    models.CharField(
                        blank=True,
                        choices=[("SELECT", "Select"), ("YES", "Yes"), ("NO", "No")],
                        default="SELECT",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "valuation_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "booking_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "booking_fee_added_to_loan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("--SELECT--", "--Select--"),
                            ("NA", "N/A"),
                            ("YES", "Yes"),
                            ("NO", "No"),
                        ],
                        default="--SELECT--",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "procuration_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="case.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
