# Generated by Django 5.1.2 on 2025-03-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0044_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("-created_at", "-updated_at")},
        ),
    ]
