# Generated by Django 5.1.2 on 2025-03-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0045_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="application_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="application_review_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="processing_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="processing_consent_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
