# Generated by Django 5.1.2 on 2025-03-11 08:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0046_product_application_review_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DipHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "is_this_application_had_a_decision_in_principle",
                    models.BooleanField(default=False),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "lender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACCORD_MORTGAGES", "Accord Mortgages"),
                            ("AHLI_UNITED_BANK", "Ahli United Bank"),
                            ("AL_RAYAN_BANK", "Al Rayan Bank"),
                            ("ALDERMORE_MORTGAGES", "Aldermore Mortgages"),
                            ("AMICUS_PLC", "Amicus PLC"),
                            ("ASSETZ_CAPITAL", "Assetz Capital"),
                            ("ATOM_BANK", "Atom Bank"),
                            ("AVIVA_EQUITY_RELEASE", "Aviva Equity Release"),
                            ("AXIS_BANK", "Axis Bank"),
                            ("BANK_AND_CLIENTS_PLC", "Bank & Clients PLC"),
                            ("BANK_OF_CHINA", "Bank of China"),
                            ("BANK_OF_CYPRUS_UK", "Bank of Cyprus UK"),
                            ("BANK_OF_IRELAND", "Bank of Ireland"),
                            ("BARCLAYS", "Barclays"),
                            ("BARCLAYS_COMMERCIAL", "Barclays Commercial"),
                            ("BATH_BUILDING_SOCIETY", "Bath Building Society"),
                            ("BEVERLEY_BUILDING_SOCIETY", "Beverley Building Society"),
                            ("BLUESTONE_MORTGAGES", "Bluestone Mortgages"),
                            ("BLUEZEST", "BlueZest"),
                            ("BM_SOLUTIONS", "BM Solutions"),
                            ("BOOST_CAPITAL", "Boost Capital"),
                            (
                                "BRIDGEWATER_EQUITY_RELEASE",
                                "Bridgewater Equity Release",
                            ),
                            (
                                "BUCKINGHAMSHIRE_BUILDING_SOCIETY",
                                "Buckinghamshire Building Society",
                            ),
                            (
                                "CAMBRIDGE_AND_COUNTIES_BANK",
                                "Cambridge and Counties Bank",
                            ),
                            (
                                "CAMBRIDGE_BUILDING_SOCIETY",
                                "Cambridge Building Society",
                            ),
                            ("CENTRAL_TRUST", "Central Trust"),
                            ("CHARTERBANK", "Charterbank"),
                            ("CHL_MORTGAGES", "CHL Mortgages"),
                            (
                                "CHORLEY_DISTRICT_BUILDING_SOCIETY",
                                "Chorley & District Building Society",
                            ),
                            ("CLEARLY_LOANS", "Clearly Loans"),
                            ("COUTTS", "Coutts"),
                            ("COVENTRY_BUILDING_SOCIETY", "Coventry Building Society"),
                            ("CROWN_EQUITY_RELEASE", "Crown Equity Release"),
                            (
                                "CUMBERLAND_BUILDING_SOCIETY",
                                "Cumberland Building Society",
                            ),
                            ("DANSKE_BANK", "Danske Bank"),
                            (
                                "DARLINGTON_BUILDING_SOCIETY",
                                "Darlington Building Society",
                            ),
                            ("DIGITAL_MORTGAGES", "Digital Mortgages"),
                            ("DUDLEY_BUILDING_SOCIETY", "Dudley Building Society"),
                            (
                                "EARL_SHILTON_BUILDING_SOCIETY",
                                "Earl Shilton Building Society",
                            ),
                            ("ECOLOGY_BUILDING_SOCIETY", "Ecology Building Society"),
                            ("EQUIFINANCE", "Equifinance"),
                            ("FAMILY_BUILDING_SOCIETY", "Family Building Society"),
                            ("FINSEC", "FinSec"),
                            ("FIRST_TRUST_BANK", "First Trust Bank"),
                            ("FLEET_MORTGAGES", "Fleet Mortgages"),
                            ("FOUNDATION_HOME_LOANS", "Foundation Home Loans"),
                            ("FURNESS_BUILDING_SOCIETY", "Furness Building Society"),
                            ("GATEHOUSE_BANK", "Gatehouse Bank"),
                            ("GENERATION_HOME", "Generation Home"),
                            ("GODIVA_MORTGAGES", "Godiva Mortgages"),
                            ("HALIFAX", "Halifax"),
                            ("HAMPSHIRE_TRUST_BANK", "Hampshire Trust Bank"),
                            ("HANDELSBANKEN", "Handelsbanken"),
                            (
                                "HANLEY_ECONOMIC_BUILDING_SOCIETY",
                                "Hanley Economic Building Society",
                            ),
                            ("HARPDEN_BUILDING_SOCIETY", "Harpenden Building Society"),
                            ("HSBC", "HSBC"),
                            ("ICICI_BANK", "ICICI Bank"),
                            ("INTERBAY_COMMERCIAL", "Interbay Commercial"),
                            ("INVESTEC", "Investec"),
                            ("IPSWICH_BUILDING_SOCIETY", "Ipswich Building Society"),
                            ("JUST_RETIREMENT_SOLUTIONS", "Just Retirement Solutions"),
                            ("KENSINGTON_MORTGAGES", "Kensington Mortgages"),
                            ("KENT_RELIANCE", "Kent Reliance"),
                            ("KEYSTONE_PROPERTY_FINANCE", "Keystone Property Finance"),
                            ("LEEDS_BUILDING_SOCIETY", "Leeds Building Society"),
                            (
                                "LEEK_UNITED_BUILDING_SOCIETY",
                                "Leek United Building Society",
                            ),
                            ("METRO_BANK", "Metro Bank"),
                            (
                                "MONMOUTHSHIRE_BUILDING_SOCIETY",
                                "Monmouthshire Building Society",
                            ),
                            ("NATIONWIDE", "Nationwide"),
                            ("NATWEST", "NatWest"),
                            (
                                "NOTTINGHAM_BUILDING_SOCIETY",
                                "Nottingham Building Society",
                            ),
                            ("PARAGON_MORTGAGES", "Paragon Mortgages"),
                            ("PEPPER_MONEY", "Pepper Money"),
                            ("POST_OFFICE_MORTGAGES", "Post Office Mortgages"),
                            (
                                "PRINCIPALITY_BUILDING_SOCIETY",
                                "Principality Building Society",
                            ),
                            ("SANTANDER", "Santander"),
                            ("SKIPTON_BUILDING_SOCIETY", "Skipton Building Society"),
                            ("TSB", "TSB"),
                            ("ULSTER_BANK", "Ulster Bank"),
                            ("UNKNOWN", "Unknown"),
                            ("UNKNOWN_DEFAULT", "Unknown (Default)"),
                            ("VIDA_HOMELOANS", "Vida Homeloans"),
                            (
                                "WEST_BROMWICH_BUILDING_SOCIETY",
                                "West Bromwich Building Society",
                            ),
                            ("WEST_ONE_LOANS", "West One Loans"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("dip_date", models.DateField(blank=True, null=True)),
                (
                    "dip_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("REFERED", "Refered"),
                        ],
                        default="ACCEPTED",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "dip_reference_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dip_history",
                        to="case.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
