# Generated by Django 5.1.2 on 2025-03-11 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0048_alter_diphistory_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "fees",
                    models.CharField(
                        blank=True,
                        choices=[("FEES_IN", "Fees In"), ("FEES_OUT", "Fees Out")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "fee_in_type",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("BROKER_COMMITMENT_FEE", "Broker Commit Fee"),
                            ("PROCURATION_FEE", "Procuration Fee"),
                            ("MORTGAGE_OFFER_FEE", "Mortgage Offer Fee"),
                            ("BROKER_FEE", "Broker Fee"),
                            ("OTHER", "Other"),
                        ],
                        default="UNKNOWN",
                        max_length=255,
                    ),
                ),
                (
                    "fee_out_type",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("COMMISSION_PROC_FEE_SHARE", "Commission Proc Fee Share"),
                        ],
                        default="UNKNOWN",
                        max_length=255,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CREDIT_DEBIT_CARD", "Credit Debit Card"),
                            ("BACS", "BACS"),
                            ("CHEQUE", "Cheque"),
                            ("CASH", "Cash"),
                            ("ONLINE", "Online"),
                            ("OTHER", "Other"),
                        ],
                        default="CREDIT_DEBIT_CARD",
                        max_length=255,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                ("date_received", models.DateField(blank=True, null=True)),
                ("date_paid_out", models.DateField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="case.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
    ]
