# Generated by Django 5.1.2 on 2025-03-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0049_fees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fees",
            name="fee_in_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("BROKER_COMMITMENT_FEE", "Broker Commit Fee"),
                    ("PROCURATION_FEE", "Procuration Fee"),
                    ("MORTGAGE_OFFER_FEE", "Mortgage Offer Fee"),
                    ("BROKER_FEE", "Broker Fee"),
                    ("OTHER", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fees",
            name="fee_out_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("COMMISSION_PROC_FEE_SHARE", "Commission Proc Fee Share"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
