# Generated by Django 5.1.2 on 2025-03-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0053_existingprotection_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitoraccountant",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
