# Generated by Django 5.1.2 on 2025-03-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0054_solicitoraccountant_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitoraccountant",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="solicitoraccountant",
            name="contact_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="solicitoraccountant",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="solicitoraccountant",
            name="dx_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="solicitoraccountant",
            name="fax_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="solicitoraccountant",
            name="qualifications",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="solicitoraccountant",
            name="street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
