# Generated by Django 5.1.2 on 2025-03-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0055_alter_solicitoraccountant_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="note",
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
