# Generated by Django 5.1.2 on 2025-03-18 09:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0055_alter_solicitoraccountant_city_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "property_purchase_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "property_estimated_valuation",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("have_you_found_a_property_yet", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                ("postcode", models.CharField(max_length=50)),
                (
                    "house_name_or_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("address_one", models.CharField(max_length=100)),
                (
                    "address_two",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(max_length=50)),
                ("county", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("PLEASE_SELECT_A_REGION", "Please Select a Region"),
                            ("NORTH", "North"),
                            ("NORTH_WEST", "North West"),
                            ("YORKSHIRE_AND_HUMBERSIDE", "Yorkshire and Humberside"),
                            ("EAST_MIDLANDS", "East Midlands"),
                            ("WEST_MIDLANDS", "West Midlands"),
                            ("EAST_ANGLIA", "East Anglia"),
                            ("LONDON", "London"),
                            ("SOUTH_EAST", "South East (Not London)"),
                            ("SOUTH_WEST", "South West"),
                            ("WALES", "Wales"),
                            ("SCOTLAND", "Scotland"),
                            ("NORTHERN_IRELAND", "Northern Ireland"),
                        ],
                        default="PLEASE_SELECT_A_REGION",
                        max_length=50,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("UNITED_KINGDOM", "United Kingdom"),
                            ("ENGLAND", "England"),
                            ("SCOTLAND", "Scotland"),
                            ("WALES", "Wales"),
                            ("NORTHERN_IRELAND", "Northern Ireland"),
                        ],
                        default="UNITED_KINGDOM",
                        max_length=50,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("SELECT", "Select"),
                            ("HOUSE", "House"),
                            ("FLAT", "Flat"),
                            ("MAISONETTE", "Maisonette"),
                            ("BUNGALOW", "Bungalow"),
                            ("WAREHOUSE", "Warehouse"),
                            ("LAND", "Land"),
                            ("COMMERCIAL", "Commercial"),
                            ("SEMI_COMMERCIAL", "Semi-Commercial"),
                            ("MULTI_UNIT_BLOCK", "Multi-Unit Block"),
                            ("HMO", "HMO"),
                        ],
                        default="SELECT",
                        max_length=50,
                    ),
                ),
                (
                    "house_type",
                    models.CharField(
                        choices=[
                            ("SELECT", "Select"),
                            ("DETACHED", "Detached"),
                            ("SEMI_DETACHED", "Semi-Detached"),
                            ("MID_TERRACED", "Mid-Terraced"),
                            ("END_TERRACED", "End-Terraced"),
                            ("TOWN_HOUSE", "Town House"),
                        ],
                        default="SELECT",
                        max_length=50,
                    ),
                ),
                (
                    "flat_type",
                    models.CharField(
                        choices=[
                            ("SELECT", "Select"),
                            ("PURPOSE_BUILT", "Purpose Built"),
                            ("CONVERTED", "Converted"),
                            ("STUDIO", "Studio"),
                        ],
                        default="SELECT",
                        max_length=50,
                    ),
                ),
                (
                    "construction_of_walls",
                    models.CharField(
                        choices=[
                            (
                                "PLEASE_SELECT_A_CONSTRUCTION_TYPE",
                                "Please Select A Construction Type",
                            ),
                            ("CONCRETE", "Concrete"),
                            ("TIMBER_FRAMED", "Timber Framed"),
                            ("STEEL_FRAMED", "Steel Framed"),
                            ("BRICK", "Brick"),
                            ("MUNDIC_BLOCK", "Mundic Block"),
                            (
                                "PRC_REPAIR_WITH_CERTIFICATE",
                                "PRC Repair with Certificate",
                            ),
                            ("STONE", "Stone"),
                            ("COB", "Cob"),
                        ],
                        default="PLEASE_SELECT_A_CONSTRUCTION_TYPE",
                        max_length=50,
                    ),
                ),
                (
                    "construction_of_roof",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TILE_ANY_TYPE", "Tile (Any Type)"),
                            ("CLAY_TILE", "Clay Tile"),
                            ("SLATE_TILE", "Slate Tile"),
                            ("CONCRETE_TILE", "Concrete Tile"),
                            ("FLAT", "Flat"),
                            ("THATCHED", "Thatched"),
                            ("METAL", "Metal"),
                            ("WOOD", "Wood"),
                            (
                                "PLASTIC_EG_EPDM_PVC_CPE",
                                "Plastic (e.g. EPDM, PVC, CPE)",
                            ),
                            ("BITUMEN", "Bitumen"),
                            ("GREEN_ROOF", "Green Roof"),
                            ("SHINGLES", "Shingles"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "bedrooms",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "bathrooms",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "reception_rooms",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "kitchens",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "garages",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "parking_spaces",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("ONE", "One"),
                            ("TWO", "Two"),
                            ("THREE", "Three"),
                            ("FOUR", "Four"),
                            ("FIVE", "Five"),
                            ("SIX", "Six"),
                            ("SEVEN", "Seven"),
                            ("EIGHT", "Eight"),
                            ("NINE", "Nine"),
                            ("TEN", "Ten"),
                        ],
                        default="ONE",
                        max_length=50,
                    ),
                ),
                (
                    "epc_rating",
                    models.CharField(
                        choices=[
                            ("SELECT", "Select"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                        ],
                        default="SELECT",
                        max_length=50,
                    ),
                ),
                ("floor", models.PositiveIntegerField()),
                ("flats", models.PositiveIntegerField()),
                ("number_of_storeys_in_the_building", models.PositiveIntegerField()),
                (
                    "year_built",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ]
                    ),
                ),
                ("lift_access", models.BooleanField(default=False)),
                (
                    "tenure",
                    models.CharField(
                        choices=[
                            ("SELECT", "Select"),
                            ("FREEHOLD", "Freehold"),
                            ("LEASEHOLD", "Leasehold"),
                            ("COMMONHOLD", "Commonhold"),
                            ("FEUDAL", "Feudal"),
                        ],
                        default="SELECT",
                        max_length=50,
                    ),
                ),
                (
                    "property_lease_term",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "service_charge_per_month",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "ground_rent_per_annum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "residential",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "commercial",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_the_property_a_listed_building",
                    models.BooleanField(default=False),
                ),
                ("number_of_units", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "listed_status_of_the_building",
                    models.CharField(
                        choices=[
                            ("SELECT", "Select"),
                            ("GRADE_I", "Grade I"),
                            ("GRADE_II*", "Grade II*"),
                            ("GRADE_II", "Grade II"),
                            ("GRADE_A", "Grade A"),
                            ("GRADE_B", "Grade B"),
                            ("GRADE_C", "Grade C"),
                        ],
                        default="SELECT",
                        max_length=50,
                    ),
                ),
                (
                    "listed_building_notes",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "do_you_or_will_you_own_part_or_all_of_the_freehold",
                    models.BooleanField(default=False),
                ),
                (
                    "is_the_property_part_of_a_help_to_buy_shared_ownership_scheme",
                    models.BooleanField(default=False),
                ),
                (
                    "is_the_property_above_or_near_commercial_premises",
                    models.BooleanField(default=False),
                ),
                ("is_the_property_a_new_build", models.BooleanField(default=False)),
                (
                    "new_build_warranty_provider",
                    models.CharField(
                        choices=[
                            ("SELECT_WARRANTY_PROVIDER", "Select Warranty Provider"),
                            ("NHBC", "NHBC"),
                            ("LABC", "LABC"),
                            ("PREMIER_GUARANTEE", "Premier Guarantee"),
                            ("CHECKMATE", "Checkmate"),
                            ("BUILDSAFE", "Buildsafe"),
                            ("BUILD_ZONE", "Build Zone"),
                            ("ICW", "ICW"),
                            ("PRO_TEK", "Pro Tek"),
                            ("GLOBAL", "Global"),
                            ("OTHER", "Other"),
                        ],
                        default="SELECT_WARRANTY_PROVIDER",
                        max_length=50,
                    ),
                ),
                (
                    "other_new_build_warranty_rovider",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_the_property_a_right_to_buy", models.BooleanField(default=False)),
                ("date_of_purchase", models.DateField(blank=True, null=True)),
                (
                    "discounted_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_the_property_ex_local_authority",
                    models.BooleanField(default=False),
                ),
                (
                    "is_this_property_being_purchased_from_the_council_with_this_application",
                    models.BooleanField(default=False),
                ),
                (
                    "is_there_an_annexe_within_the_property",
                    models.BooleanField(default=False),
                ),
                (
                    "will_the_property_be_owner_occupied",
                    models.BooleanField(default=False),
                ),
                (
                    "please_provide_further_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_the_property_on_the_market", models.BooleanField(default=False)),
                (
                    "is_the_property_rented_out_to_be_rented_out",
                    models.BooleanField(default=False),
                ),
                (
                    "is_the_property_standard_construction",
                    models.BooleanField(default=False),
                ),
                (
                    "comments_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "does_the_property_have_solar_panels",
                    models.BooleanField(default=False),
                ),
                ("do_you_own_the_solar_panels", models.BooleanField(default=False)),
                (
                    "is_the_property_used_purely_for_residential_purposes",
                    models.BooleanField(default=False),
                ),
                (
                    "valuation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("standard_val", "Standard Val"),
                            ("homebuyers", "Homebuyers"),
                            (
                                "full_standard_building_survey",
                                "Full Standard Building Survey",
                            ),
                            ("avm", "AVM"),
                            ("drive_by", "Drive By"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "select_applicant_list",
                    models.CharField(
                        choices=[("SELECT", "Select"), ("demo_x", "Demo X")],
                        default="SELECT",
                        max_length=50,
                    ),
                ),
                (
                    "contact_for_access",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contacts_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contacts_daytime_telephone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "contacts_mobile_telephone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "contacts_email_address",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("partner", "Partner"),
                            ("spouse", "Spouse"),
                            ("sibling", "Sibling"),
                            ("parent", "Parent"),
                            ("carer", "Carer"),
                            ("family", "Family"),
                            ("other_family", "Other Family"),
                            ("other", "Other"),
                            ("child", "Child"),
                            ("civil_partner", "Civil Partner"),
                            ("son", "Son"),
                            ("daughter", "Daughter"),
                            ("grandparent", "Grandparent"),
                            ("brother", "Brother"),
                            ("sister", "Sister"),
                            ("uncle_aunt", "Uncle/Aunt"),
                            ("foster_adoptive_parents", "Foster/Adoptive Parents"),
                            ("legal_guardian", "Legal Guardian"),
                        ],
                        default="partner",
                        max_length=50,
                    ),
                ),
                (
                    "estimated_value",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
    ]
