# Generated by Django 5.1.2 on 2025-03-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0056_propertydetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertydetails",
            name="is_this_property_being_purchased_from_the_council_with_this_application",
            field=models.BooleanField(
                db_column="purchased_from_council_with_app", default=False
            ),
        ),
    ]
