# Generated by Django 5.1.2 on 2025-03-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0056_notes_note"),
        (
            "case",
            "0057_alter_propertydetails_is_this_property_being_purchased_from_the_council_with_this_application",
        ),
    ]

    operations = []
