# Generated by Django 5.1.2 on 2025-03-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0058_merge_20250318_0928"),
    ]

    operations = [
        migrations.AlterField(
            model_name="existingprotection",
            name="policy_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LIFT_ASSURANCE_LEVEL", "Lift Assurance Level"),
                    ("LIFT_ASSURANCE_DECREASING", "Lift Assurance Decreasing"),
                    (
                        "CRITICAL_ILLNESS_COVER_DECREASING",
                        "Critical Illness Cover Decreasing",
                    ),
                    ("MORTGAGE_PAYMENT_PROTECTION", "Mortgage Payment Protection"),
                    ("BUILDINGS_AND_CONTENTS", "Buildings And Contents"),
                    ("PRIVATE_PENSION", "Private Pension"),
                    ("DEATH_IN_SERVICE_BENEFIT", "Death In Service Benefit"),
                    ("OTHER", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
