# Generated by Django 5.1.2 on 2025-03-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0059_alter_existingprotection_policy_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="existingprotection",
            name="policy_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LIFE_ASSURANCE_LEVEL", "Life Assurance Level"),
                    ("LIFE_ASSURANCE_DECREASING", "Life Assurance Decreasing"),
                    ("CRITICAL_ILLNESS_COVER_LEVEL", "Critical Illness Cover Level"),
                    (
                        "CRITICAL_ILLNESS_COVER_DECREASING",
                        "Critical Illness Cover Decreasing",
                    ),
                    ("MORTGAGE_PAYMENT_PROTECTION", "Mortgage Payment Protection"),
                    ("BUILDINGS_AND_CONTENTS", "Buildings And Contents"),
                    ("PRIVATE_PENSION", "Private Pension"),
                    ("DEATH_IN_SERVICE_BENEFIT", "Death In Service Benefit"),
                    ("OTHER", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
