# Generated by Django 5.1.2 on 2025-03-20 05:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0060_alter_existingprotection_policy_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertydetails",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="propertydetails",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="propertydetails",
            name="relationship",
        ),
        migrations.AddField(
            model_name="propertydetails",
            name="case",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_details",
                to="case.case",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="OtherOccupants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("partner", "Partner"),
                            ("spouse", "Spouse"),
                            ("sibling", "Sibling"),
                            ("parent", "Parent"),
                            ("carer", "Carer"),
                            ("family", "Family"),
                            ("other_family", "Other Family"),
                            ("other", "Other"),
                            ("child", "Child"),
                            ("civil_partner", "Civil Partner"),
                            ("son", "Son"),
                            ("daughter", "Daughter"),
                            ("grandparent", "Grandparent"),
                            ("brother", "Brother"),
                            ("sister", "Sister"),
                            ("uncle_aunt", "Uncle/Aunt"),
                            ("foster_adoptive_parents", "Foster/Adoptive Parents"),
                            ("legal_guardian", "Legal Guardian"),
                        ],
                        default="partner",
                        max_length=50,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_occupants",
                        to="case.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
