# Generated by Django 5.1.2 on 2025-03-20 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0062_budgetplanner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budgetplanner",
            options={"ordering": ("-created_at", "-updated_at")},
        ),
        migrations.AlterModelOptions(
            name="otheroccupants",
            options={"ordering": ("-created_at", "-updated_at")},
        ),
        migrations.AddField(
            model_name="budgetplanner",
            name="case",
            field=models.OneToOneField(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_planner",
                to="case.case",
            ),
            preserve_default=False,
        ),
    ]
