# Generated by Django 5.1.2 on 2025-03-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0064_creditcommitments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creditcommitments",
            options={"ordering": ("-created_at", "-updated_at")},
        ),
    ]
