# Generated by Django 5.1.2 on 2025-03-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0065_alter_creditcommitments_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="creditcommitments",
            old_name="Joint",
            new_name="joint",
        ),
    ]
