# Generated by Django 5.1.2 on 2025-03-21 06:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0066_rename_joint_creditcommitments_joint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MortgageNeeds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "repayment_method",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "monthly_mortgage_payments",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "specific_mortgage_deal",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "referred_monthly_budget",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "retirement_age",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "what_suitable_mortgage_features_are_important",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                ("front_costs", models.BooleanField(default=False)),
                ("is_ability_to_make_overpayments", models.BooleanField(default=False)),
                ("is_early_repayment_charges", models.BooleanField(default=False)),
                (
                    "is_minimise_any_lender_arrangement_costs",
                    models.BooleanField(default=False),
                ),
                (
                    "is_ability_to_add_fees_to_the_mortgage",
                    models.BooleanField(default=False),
                ),
                ("is_ability_to_add_fees_mortgage", models.BooleanField(default=False)),
                ("cashback", models.BooleanField(default=False)),
                ("portability", models.BooleanField(default=False)),
                ("guarantor_jbsp", models.BooleanField(default=False)),
                ("offset_mortgage", models.BooleanField(default=False)),
                ("scheme_specific", models.BooleanField(default=False)),
                ("speed_of_completion", models.BooleanField(default=False)),
                ("sharia_compliant_mortgages", models.BooleanField(default=False)),
                ("ltd_company_btl", models.BooleanField(default=False)),
                ("any_incentives", models.BooleanField(default=False)),
                (
                    "considering_debt_consolidation",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "anticipate_any_changes_notes",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                ("anticipate_any_changes", models.BooleanField(default=False)),
                ("life_cover", models.BooleanField(default=False)),
                ("critical_illness", models.BooleanField(default=False)),
                ("income_protection", models.BooleanField(default=False)),
                ("asu", models.BooleanField(default=False)),
                ("pmi", models.BooleanField(default=False)),
                ("family_income_benefit", models.BooleanField(default=False)),
                ("buildings_and_contents", models.BooleanField(default=False)),
                ("buildings", models.BooleanField(default=False)),
                ("contents", models.BooleanField(default=False)),
                ("accidental_damage", models.BooleanField(default=False)),
                ("landlords_cover", models.BooleanField(default=False)),
                ("home_emergency_cover", models.BooleanField(default=False)),
                ("personal_possessions_cover", models.BooleanField(default=False)),
                ("personal_possessions_confirm", models.BooleanField(default=False)),
                ("have_you_a_will_in_place", models.BooleanField(default=False)),
                (
                    "have_you_a_will_in_place_note",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "mortgage_requirements_note",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                ("mortgage_requirements", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=700, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortgage_needs",
                        to="case.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
    ]
