# Generated by Django 5.1.2 on 2025-03-21 06:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0067_mortgageneeds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mortgageneeds",
            name="asu",
        ),
        migrations.RemoveField(
            model_name="mortgageneeds",
            name="buildings_and_contents",
        ),
        migrations.RemoveField(
            model_name="mortgageneeds",
            name="critical_illness",
        ),
        migrations.RemoveField(
            model_name="mortgageneeds",
            name="family_income_benefit",
        ),
        migrations.RemoveField(
            model_name="mortgageneeds",
            name="income_protection",
        ),
        migrations.RemoveField(
            model_name="mortgageneeds",
            name="life_cover",
        ),
        migrations.RemoveField(
            model_name="mortgageneeds",
            name="pmi",
        ),
        migrations.CreateModel(
            name="MortgageFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("life_cover", models.BooleanField(default=False)),
                ("critical_illness", models.BooleanField(default=False)),
                ("income_protection", models.BooleanField(default=False)),
                ("asu", models.BooleanField(default=False)),
                ("pmi", models.BooleanField(default=False)),
                ("family_income_benefit", models.BooleanField(default=False)),
                ("buildings_and_contents", models.BooleanField(default=False)),
                (
                    "MortgageNeeds",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortgage_features",
                        to="case.mortgageneeds",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
    ]
