# Generated by Django 5.1.2 on 2025-03-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0067_mortgagefeatures_mortgageneeds"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fees",
            old_name="fees",
            new_name="fees_type",
        ),
    ]
