# Generated by Django 5.1.2 on 2025-03-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0068_rename_fees_fees_fees_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertydetails",
            name="address_one",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="propertydetails",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="propertydetails",
            name="flats",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="propertydetails",
            name="floor",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="propertydetails",
            name="number_of_storeys_in_the_building",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="propertydetails",
            name="postcode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
