# Generated by Django 5.1.2 on 2025-03-24 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0069_alter_propertydetails_address_one_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertydetails",
            name="year_built",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9999),
                ],
            ),
        ),
    ]
