# Generated by Django 5.1.2 on 2025-03-24 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0070_alter_propertydetails_year_built"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetplanner",
            name="post_debt_repayments",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_debt_repayments",
                to="case.debtrepayments",
            ),
        ),
    ]
