# Generated by Django 5.1.2 on 2025-03-24 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0071_alter_budgetplanner_post_debt_repayments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mortgagefeatures",
            name="applicant",
            field=models.ManyToManyField(
                related_name="mortgage_features_applicant", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
