# Generated by Django 5.1.2 on 2025-03-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0072_mortgagefeatures_applicant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="initial_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
