# Generated by Django 5.1.2 on 2025-04-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0073_alter_product_initial_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcommitments",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CREDIT_CARD", "Credit Card"),
                    ("STORE_CARD", "Store Card"),
                    ("LOAN", "Loan"),
                    ("HP", "HP"),
                    ("OVERDRAFT", "Overdraft"),
                    ("STUDENT_LOAN", "Student Loan"),
                    ("MAINTENANCE", "Maintenance"),
                    ("LEASE", "Lease"),
                    ("UNSECURED", "Unsecured"),
                    ("MORTGAGE_RENT", "Mortgage / Rent"),
                    ("PUBLIC_UTILITY", "Public Utility"),
                    ("COMMUNICATIONS", "Communications"),
                    ("INSURANCE", "Insurance"),
                    ("SECURED", "Secured"),
                    ("PCP", "PCP"),
                    ("MAIL_ORDER", "Mail Order"),
                    ("CHILDCARE", "Childcare"),
                    ("CAR_FINANCE", "Car Finance"),
                    ("BNPL", "Buy Now Pay Later (BNPL)"),
                    ("CREDIT_COMMITMENT", "Credit Commitment"),
                    ("DMP", "DMP"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
