# Generated by Django 5.1.2 on 2025-04-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0074_alter_creditcommitments_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcommitments",
            name="account_no",
            field=models.CharField(blank=True, null=True),
        ),
    ]
