# Generated by Django 5.1.2 on 2025-04-22 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0075_alter_creditcommitments_account_no"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("answer", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="DisadvantageRisks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "question_one",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_four",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_four_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_five",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_five_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_six",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_six_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_seven",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_seven_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_eight",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_eight_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_nine",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_nine_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "extra_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disadvantage_extra_questions",
                        to="case.extraquestion",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="CostsFees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "question_one",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "extra_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs_fees_extra_questions",
                        to="case.extraquestion",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="CostAdvice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "question_one",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "extra_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_advice_extra_questions",
                        to="case.extraquestion",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="CircumstancesObjectives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "question_one",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "extra_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circumstances_extra_questions",
                        to="case.extraquestion",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="BuildingsInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "question_one",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_four",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_four_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_five_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "extra_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildings_insurance_extra_questions",
                        to="case.extraquestion",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="BudgetAffordability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "question_one",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "extra_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_extra_questions",
                        to="case.extraquestion",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="NewMortgageDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "question_one",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "extra_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortgage_details_extra_questions",
                        to="case.extraquestion",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="Protection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "question_one",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_four",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_four_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_four_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "extra_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protection_extra_questions",
                        to="case.extraquestion",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="RecommendingMortgageAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "question_one",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "extra_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortgage_amount_extra_questions",
                        to="case.extraquestion",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="RecommendingMortgageLender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "question_one",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "extra_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lender_extra_questions",
                        to="case.extraquestion",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="RecommendingMortgageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "question_one",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_four",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_four_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "extra_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortgage_type_extra_questions",
                        to="case.extraquestion",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="RecommendingRepaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "question_one",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_four",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_four_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_five",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_five_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "extra_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayment_method_extra_questions",
                        to="case.extraquestion",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="RecommendingTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "question_one",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "extra_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_extra_questions",
                        to="case.extraquestion",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="Wills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "question_one",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_one_sharia",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_two_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "question_three_answer",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "extra_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wills_extra_questions",
                        to="case.extraquestion",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="Suitability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "budget_affordability",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_affordability",
                        to="case.budgetaffordability",
                    ),
                ),
                (
                    "buildings_insurance",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildingsInsurance",
                        to="case.buildingsinsurance",
                    ),
                ),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suitability",
                        to="case.case",
                    ),
                ),
                (
                    "cost_advice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_advice",
                        to="case.costadvice",
                    ),
                ),
                (
                    "costs_fees",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs_fees",
                        to="case.costsfees",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "disadvantage_risks",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disadvantage_risks",
                        to="case.disadvantagerisks",
                    ),
                ),
                (
                    "new_mortgage_details",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_mortgage_details",
                        to="case.newmortgagedetails",
                    ),
                ),
                (
                    "protection",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protection",
                        to="case.protection",
                    ),
                ),
                (
                    "recommending_mortgage_amount",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommending_mortgage_amount",
                        to="case.recommendingmortgageamount",
                    ),
                ),
                (
                    "recommending_mortgage_lender",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommending_mortgage_lender",
                        to="case.recommendingmortgagelender",
                    ),
                ),
                (
                    "recommending_mortgage_type",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommending_mortgage_type",
                        to="case.recommendingmortgagetype",
                    ),
                ),
                (
                    "recommending_repayment_method",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommending_repayment_method",
                        to="case.recommendingrepaymentmethod",
                    ),
                ),
                (
                    "recommending_term",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommending_term",
                        to="case.recommendingterm",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "wills",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wills",
                        to="case.wills",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
    ]
