# Generated by Django 5.1.2 on 2025-04-24 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0076_extraquestion_disadvantagerisks_costsfees_costadvice_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Compliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("date_file_checked", models.DateField(blank=True, null=True)),
                ("date_file_rechecked", models.DateField(blank=True, null=True)),
                ("file_checked", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "remedial_actions_required",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Yes"), ("NO", "No")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "remedial_actions_complete",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Yes"), ("NO", "No")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True, max_length=1000, null=True)),
                ("rating_a", models.BooleanField(default=False)),
                ("rating_b", models.BooleanField(default=False)),
                ("rating_c", models.BooleanField(default=False)),
                (
                    "terms_of_business",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "terms_of_business_text",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "privacy_notice",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "privacy_notice_text",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "fee_agreement",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "fee_agreement_text",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance",
                        to="case.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
    ]
