# Generated by Django 5.1.2 on 2025-04-24 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0077_otherquestion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otherquestion",
            name="extra_question",
        ),
    ]
