# Generated by Django 5.1.2 on 2025-04-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0079_merge_0077s"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otherquestion",
            options={"ordering": ("-created_at",)},
        ),
    ]
