# Generated by Django 5.1.2 on 2025-04-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0080_alter_otherquestion_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otherquestion",
            options={"ordering": ("-created_at", "-updated_at")},
        ),
    ]
