# Generated by Django 5.1.2 on 2025-04-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0081_alter_otherquestion_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budgetaffordability",
            name="extra_question",
        ),
        migrations.RemoveField(
            model_name="buildingsinsurance",
            name="extra_question",
        ),
        migrations.RemoveField(
            model_name="circumstancesobjectives",
            name="extra_question",
        ),
        migrations.RemoveField(
            model_name="costadvice",
            name="extra_question",
        ),
        migrations.RemoveField(
            model_name="costsfees",
            name="extra_question",
        ),
        migrations.RemoveField(
            model_name="disadvantagerisks",
            name="extra_question",
        ),
        migrations.RemoveField(
            model_name="newmortgagedetails",
            name="extra_question",
        ),
        migrations.RemoveField(
            model_name="protection",
            name="extra_question",
        ),
        migrations.RemoveField(
            model_name="recommendingmortgageamount",
            name="extra_question",
        ),
        migrations.RemoveField(
            model_name="recommendingmortgagelender",
            name="extra_question",
        ),
        migrations.RemoveField(
            model_name="recommendingmortgagetype",
            name="extra_question",
        ),
        migrations.RemoveField(
            model_name="recommendingrepaymentmethod",
            name="extra_question",
        ),
        migrations.RemoveField(
            model_name="recommendingterm",
            name="extra_question",
        ),
        migrations.RemoveField(
            model_name="wills",
            name="extra_question",
        ),
    ]
