# Generated by Django 5.1.2 on 2025-04-28 08:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0082_remove_budgetaffordability_extra_question_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("answer", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "BudgetAffordability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_affordability_extra_answers",
                        to="case.budgetaffordability",
                    ),
                ),
                (
                    "BuildingsInsurance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildings_insurance_extra_answers",
                        to="case.buildingsinsurance",
                    ),
                ),
                (
                    "CircumstancesObjectives",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circumstances_extra_answers",
                        to="case.circumstancesobjectives",
                    ),
                ),
                (
                    "CostAdvice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_advice_extra_answers",
                        to="case.costadvice",
                    ),
                ),
                (
                    "CostsFees",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs_fees_extra_answers",
                        to="case.costsfees",
                    ),
                ),
                (
                    "DisadvantageRisks",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disadvantage_risks_extra_answers",
                        to="case.disadvantagerisks",
                    ),
                ),
                (
                    "NewMortgageDetails",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_mortgage_details_extra_answers",
                        to="case.newmortgagedetails",
                    ),
                ),
                (
                    "Protection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protection_extra_answers",
                        to="case.protection",
                    ),
                ),
                (
                    "RecommendingMortgageAmount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommending_mortgage_amount_extra_answers",
                        to="case.recommendingmortgageamount",
                    ),
                ),
                (
                    "RecommendingMortgageLender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommending_mortgage_lender_extra_answers",
                        to="case.recommendingmortgagelender",
                    ),
                ),
                (
                    "RecommendingMortgageType",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommending_mortgage_type_extra_answers",
                        to="case.recommendingmortgagetype",
                    ),
                ),
                (
                    "RecommendingRepaymentMethod",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommending_repayment_method_extra_answers",
                        to="case.recommendingrepaymentmethod",
                    ),
                ),
                (
                    "RecommendingTerm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommending_term_extra_answers",
                        to="case.recommendingterm",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_answers",
                        to="case.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "wills",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wills_extra_answers",
                        to="case.wills",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
        migrations.DeleteModel(
            name="OtherQuestion",
        ),
    ]
