# Generated by Django 5.1.2 on 2025-04-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0082_remove_budgetaffordability_extra_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliance",
            name="affordability_calculator",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="affordability_calculator_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="agreement_in_principle",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="agreement_in_principle_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="are_cost_and_fees_been_complete_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="are_cost_and_fees_been_completed",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="are_disadvantages_risks_been_selected",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="are_disadvantages_risks_been_selected_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="are_fees_disclosed_correctly",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="are_fees_disclosed_correctly_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="are_results_stored_in_order_of_client_preference",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="are_results_stored_in_order_of_client_preference_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="are_we_recommending_mortgage_amount",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="are_we_recommending_mortgage_amount_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="are_we_recommending_mortgage_lender",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="are_we_recommending_mortgage_lender_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="are_we_recommending_mortgage_term",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="are_we_recommending_mortgage_term_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="are_we_recommending_mortgage_type",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="are_we_recommending_mortgage_type_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="are_we_recommending_repayment_method",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="are_we_recommending_repayment_method_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="bank_statements",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="bank_statements_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="credit_reports",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="credit_reports_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="debt_consolidation_calculator",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="debt_consolidation_calculator_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_employment_and_income_details_match",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_employment_and_income_details_match_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_figures_features_mortgage_requirement_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_figures_features_mortgage_requirements",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_figures_stated_in_mortgage_requirements",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_figures_stated_in_mortgage_requirements_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_monthly_payment_fit_within_disposable_income",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_monthly_payment_fit_within_disposable_income_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_mortgage_application_confirm",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_mortgage_application_confirm_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_property_loan_details_match",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_property_loan_details_match_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_recommended_product_match_your_needs_section",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_recommended_product_match_your_needs_section_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_the_occupation_compared",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_the_occupation_compared_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_the_stated_income",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_the_stated_income_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_the_stated_net_income",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="does_the_stated_net_income_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="employment_details",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="employment_details_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="evidence_of_research",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="evidence_of_research_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="factfind_filled",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="factfind_filled_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="financial_sanctions_checked",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="financial_sanctions_checked_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_accountant_solicitor_details_confirmed",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_accountant_solicitor_details_confirmed_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_adviser_completed_calculator",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_adviser_completed_calculator_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_adviser_included",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_adviser_included_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_adviser_personalised",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_adviser_personalised_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_adviser_sourced_mortgage_requirement_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_adviser_sourced_mortgage_requirements",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_all_direct_debits_been_recorded",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_all_direct_debits_been_recorded_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_b_and_c_section_personalised",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_b_and_c_section_personalised_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_budget_affordability_been_personalised",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_budget_affordability_been_personalised_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_budget_planner_been_completed",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_budget_planner_been_completed_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_circumstances_objectives_personalised",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_circumstances_objectives_personalised_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_client_adverse_credit",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_client_adverse_credit_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_credit_commitments_fully_completed",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_credit_commitments_fully_completed_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_due_diligence_been_completed",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_due_diligence_been_completed_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_illustration_been_produced",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_illustration_been_produced_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_meeting_discussion_been_personalised",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_meeting_discussion_been_personalised_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_mortgage_section_one_personalised",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_mortgage_section_one_personalised_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_mortgage_section_two_personalised",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_mortgage_section_two_personalised_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_new_mortgage_details_been_complete_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_new_mortgage_details_been_completed",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_product_been_fully_completed",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_product_been_fully_completed_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_property_portfolio_fully_completed",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_property_portfolio_fully_completed_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_proposed_property_details_fully_completed",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_proposed_property_details_fully_completed_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_protection_section_personalised",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_protection_section_personalised_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_reasons_for_mortgage_been_personalised",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_reasons_for_mortgage_been_personalised_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_repayment_vehicle_recorded",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_repayment_vehicle_recorded_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_source_of_lead_been_recorded",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_source_of_lead_been_recorded_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_suitability_letter_been_generated",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_suitability_letter_been_generated_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_wills_section_personalised",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_wills_section_personalised_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_your_needs_fully_completed",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="has_your_needs_fully_completed_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="have_figures_been_input",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="have_figures_been_input_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="interest_only",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="interest_only_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="is_any_credit_commitments",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="is_any_credit_commitments_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="is_applicants_live_at_separate_addresses",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="is_applicants_live_at_separate_addresses_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="is_deposit_come_from_sale_of_property",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="is_deposit_come_from_sale_of_property_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="is_recommended_product_showing_evidence_research",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="is_recommended_product_showing_evidence_research_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="is_replacement_suitability_letter",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="is_replacement_suitability_letter_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="is_the_address_on_the_kfi_correct",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="is_the_address_on_the_kfi_correct_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="is_the_client_in_an_occupation",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="is_the_client_in_an_occupation_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="lender_fees_added",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="lender_fees_added_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="loan_details_fully_completed",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="loan_details_fully_completed_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="mortgage_offer",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="mortgage_offer_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="nivo_idv_check",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="nivo_idv_check_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="personal_details",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="personal_details_match_the_factfind",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="personal_details_match_the_factfind_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="personal_details_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="post_application_changes",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="post_application_changes_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="proof_of_address",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="proof_of_address_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="proof_of_deposit",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="proof_of_deposit_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="proof_of_id",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="proof_of_id_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="proof_of_income",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="proof_of_income_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="proof_of_lending",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="proof_of_lending_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="proof_of_repayment",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="proof_of_repayment_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="realistic_proximity_to_the_advisor",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="realistic_proximity_to_the_advisor_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="retirement_age",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="retirement_age_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="shared_equity_documentation",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="shared_equity_documentation_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="signed_application",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="signed_application_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="suitability_letter",
            field=models.CharField(
                blank=True,
                choices=[("YES", "YES"), ("NO", "NO"), ("N/A", "N/A")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="suitability_letter_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
