# Generated by Django 5.1.2 on 2025-04-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0083_extraanswer_delete_otherquestion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extraanswer",
            old_name="BudgetAffordability",
            new_name="budget_affordability",
        ),
        migrations.RenameField(
            model_name="extraanswer",
            old_name="BuildingsInsurance",
            new_name="buildings_insurance",
        ),
        migrations.RenameField(
            model_name="extraanswer",
            old_name="CircumstancesObjectives",
            new_name="circumstances_objectives",
        ),
        migrations.RenameField(
            model_name="extraanswer",
            old_name="CostAdvice",
            new_name="cost_advice",
        ),
        migrations.RenameField(
            model_name="extraanswer",
            old_name="CostsFees",
            new_name="costs_fees",
        ),
        migrations.RenameField(
            model_name="extraanswer",
            old_name="DisadvantageRisks",
            new_name="disadvantage_risks",
        ),
        migrations.RenameField(
            model_name="extraanswer",
            old_name="NewMortgageDetails",
            new_name="new_mortgage_details",
        ),
        migrations.RenameField(
            model_name="extraanswer",
            old_name="Protection",
            new_name="protection",
        ),
        migrations.RenameField(
            model_name="extraanswer",
            old_name="RecommendingMortgageLender",
            new_name="recommending_mortgageLender",
        ),
        migrations.RenameField(
            model_name="extraanswer",
            old_name="RecommendingMortgageAmount",
            new_name="recommending_mortgage_amount",
        ),
        migrations.RenameField(
            model_name="extraanswer",
            old_name="RecommendingMortgageType",
            new_name="recommending_mortgage_type",
        ),
        migrations.RenameField(
            model_name="extraanswer",
            old_name="RecommendingRepaymentMethod",
            new_name="recommending_repayment_method",
        ),
        migrations.RenameField(
            model_name="extraanswer",
            old_name="RecommendingTerm",
            new_name="recommending_term",
        ),
    ]
