# Generated by Django 5.1.2 on 2025-05-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0083_compliance_affordability_calculator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetaffordability",
            name="question_one",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="budgetaffordability",
            name="question_one_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="budgetaffordability",
            name="question_one_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="budgetaffordability",
            name="question_two",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="budgetaffordability",
            name="question_two_answer",
            field=models.CharField(blank=True, max_length=710000, null=True),
        ),
        migrations.AlterField(
            model_name="budgetaffordability",
            name="question_two_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="buildingsinsurance",
            name="question_five_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="buildingsinsurance",
            name="question_four",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="buildingsinsurance",
            name="question_four_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="buildingsinsurance",
            name="question_one",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="buildingsinsurance",
            name="question_one_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="buildingsinsurance",
            name="question_one_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="buildingsinsurance",
            name="question_three",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="buildingsinsurance",
            name="question_three_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="buildingsinsurance",
            name="question_three_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="buildingsinsurance",
            name="question_two",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="buildingsinsurance",
            name="question_two_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="buildingsinsurance",
            name="question_two_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="circumstancesobjectives",
            name="question_one",
            field=models.CharField(blank=True, max_length=710000, null=True),
        ),
        migrations.AlterField(
            model_name="circumstancesobjectives",
            name="question_one_answer",
            field=models.CharField(blank=True, max_length=710000, null=True),
        ),
        migrations.AlterField(
            model_name="circumstancesobjectives",
            name="question_one_sharia",
            field=models.CharField(blank=True, max_length=710000, null=True),
        ),
        migrations.AlterField(
            model_name="circumstancesobjectives",
            name="question_three",
            field=models.CharField(blank=True, max_length=710000, null=True),
        ),
        migrations.AlterField(
            model_name="circumstancesobjectives",
            name="question_three_answer",
            field=models.CharField(blank=True, max_length=710000, null=True),
        ),
        migrations.AlterField(
            model_name="circumstancesobjectives",
            name="question_two",
            field=models.CharField(blank=True, max_length=710000, null=True),
        ),
        migrations.AlterField(
            model_name="circumstancesobjectives",
            name="question_two_answer",
            field=models.CharField(blank=True, max_length=710000, null=True),
        ),
        migrations.AlterField(
            model_name="circumstancesobjectives",
            name="question_two_sharia",
            field=models.CharField(blank=True, max_length=710000, null=True),
        ),
        migrations.AlterField(
            model_name="costadvice",
            name="question_one",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="costadvice",
            name="question_one_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="costadvice",
            name="question_one_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="costadvice",
            name="question_two",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="costadvice",
            name="question_two_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="costadvice",
            name="question_two_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="costsfees",
            name="question_one",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="costsfees",
            name="question_one_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="costsfees",
            name="question_one_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="costsfees",
            name="question_three",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="costsfees",
            name="question_three_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="costsfees",
            name="question_two",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="costsfees",
            name="question_two_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_eight",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_eight_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_five",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_five_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_four",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_four_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_nine",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_nine_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_one",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_one_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_one_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_seven",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_seven_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_six",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_six_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_three",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_three_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_two",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="disadvantagerisks",
            name="question_two_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageneeds",
            name="anticipate_any_changes_notes",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageneeds",
            name="considering_debt_consolidation",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageneeds",
            name="have_you_a_will_in_place_note",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageneeds",
            name="monthly_mortgage_payments",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageneeds",
            name="mortgage_requirements_note",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageneeds",
            name="notes",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageneeds",
            name="referred_monthly_budget",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageneeds",
            name="repayment_method",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageneeds",
            name="retirement_age",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageneeds",
            name="specific_mortgage_deal",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageneeds",
            name="what_suitable_mortgage_features_are_important",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="newmortgagedetails",
            name="question_one",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="newmortgagedetails",
            name="question_one_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="newmortgagedetails",
            name="question_one_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="newmortgagedetails",
            name="question_two",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="newmortgagedetails",
            name="question_two_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="newmortgagedetails",
            name="question_two_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="otherquestion",
            name="answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="protection",
            name="question_four",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="protection",
            name="question_four_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="protection",
            name="question_four_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="protection",
            name="question_one",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="protection",
            name="question_one_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="protection",
            name="question_one_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="protection",
            name="question_three",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="protection",
            name="question_three_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="protection",
            name="question_three_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="protection",
            name="question_two",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="protection",
            name="question_two_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="protection",
            name="question_two_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgageamount",
            name="question_one",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgageamount",
            name="question_one_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgageamount",
            name="question_one_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgageamount",
            name="question_three",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgageamount",
            name="question_three_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgageamount",
            name="question_two",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgageamount",
            name="question_two_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgagelender",
            name="question_one",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgagelender",
            name="question_one_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgagelender",
            name="question_one_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgagelender",
            name="question_three",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgagelender",
            name="question_three_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgagelender",
            name="question_two",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgagelender",
            name="question_two_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgagetype",
            name="question_four",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgagetype",
            name="question_four_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgagetype",
            name="question_one",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgagetype",
            name="question_one_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgagetype",
            name="question_one_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgagetype",
            name="question_three",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgagetype",
            name="question_three_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgagetype",
            name="question_two",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgagetype",
            name="question_two_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingmortgagetype",
            name="question_two_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingrepaymentmethod",
            name="question_five",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingrepaymentmethod",
            name="question_five_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingrepaymentmethod",
            name="question_four",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingrepaymentmethod",
            name="question_four_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingrepaymentmethod",
            name="question_one",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingrepaymentmethod",
            name="question_one_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingrepaymentmethod",
            name="question_one_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingrepaymentmethod",
            name="question_three",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingrepaymentmethod",
            name="question_three_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingrepaymentmethod",
            name="question_two",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingrepaymentmethod",
            name="question_two_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingrepaymentmethod",
            name="question_two_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingterm",
            name="question_one",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="recommendingterm",
            name="question_one_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="wills",
            name="question_one",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="wills",
            name="question_one_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="wills",
            name="question_one_sharia",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="wills",
            name="question_three",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="wills",
            name="question_three_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="wills",
            name="question_two",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="wills",
            name="question_two_answer",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
