# Generated by Django 5.1.2 on 2025-05-06 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0084_alter_budgetaffordability_question_one_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("answer", models.CharField(blank=True, max_length=10000, null=True)),
                (
                    "extra_answer_choices",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Circumstances_Objectives",
                                "Your circumstances and objectives",
                            ),
                            ("Budget_And_Affordability", "Budget And Affordability"),
                            ("New Mortgage Details", "New Mortgage Details"),
                            (
                                "Why_Are_We_Recommending_This_Repayment_Method",
                                "Why_Are_We_Recommending_This_Repayment_Method?",
                            ),
                            (
                                "Why_Are_We_Recommending_This_Mortgage_Type",
                                "Why are we recommending this mortgage type?",
                            ),
                            (
                                "Why_Are_You_Recommending_This_Term",
                                "Why are we recommending this term?",
                            ),
                            (
                                "Why_Are_We_Recommending_This_Mortgage_Lender",
                                "Why are we recommending this mortgage lender?",
                            ),
                            (
                                "Why_Are_We_Recommending_This_Mortgage_Amount",
                                "Why_Are_We_Recommending_This_Mortgage_Amount?",
                            ),
                            (
                                "What_Are_The_Costs_And_Fees",
                                "What_Are_The_Costs_And_Fees?",
                            ),
                            (
                                "What_Are_The_Disadvantages_And_Risks",
                                "What_Are_The_Disadvantages_And_Risks?",
                            ),
                            (
                                "What_Is_The_Cost_Of_Our_Advice",
                                "What_Is_The_Cost_Of_Our_Advice?",
                            ),
                            ("What_Is_The_Protection", "What_Is_The_Protection?"),
                            (
                                "What_Is_The_Buildings_Insurance",
                                "What_Is_The_Buildings_Insurance?",
                            ),
                            ("What_Is_The_Wills", "What Is The Wills?"),
                        ],
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_questions",
                        to="case.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
        migrations.DeleteModel(
            name="OtherQuestion",
        ),
    ]
