# Generated by Django 5.1.2 on 2025-04-28 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "case",
            "0084_rename_budgetaffordability_extraanswer_budget_affordability_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="extraanswer",
            old_name="recommending_mortgageLender",
            new_name="recommending_mortgage_lender",
        ),
    ]
