# Generated by Django 5.1.2 on 2025-04-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "case",
            "0085_rename_recommending_mortgagelender_extraanswer_recommending_mortgage_lender",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extraanswer",
            name="case",
        ),
    ]
