# Generated by Django 5.1.2 on 2025-05-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0085_extraanswer_delete_otherquestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extraanswer",
            name="extra_answer_choices",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "YOUR_CIRCUMSTANCES_AND_OBJECTIVES",
                        "YOUR CIRCUMSTANCES AND OBJECTIVES",
                    ),
                    ("BUDGET_AND_AFFORDABILITY", "BUDGET AND AFFORDABILITY"),
                    ("NEW_MORTGAGE_DETAILS", "NEW MORTGAGE DETAILS"),
                    (
                        "WHY_ARE_WE_RECOMMENDING_THIS_REPAYMENT_METHOD",
                        "WHY ARE WE RECOMMENDING THIS REPAYMENT METHOD?",
                    ),
                    (
                        "WHY_ARE_WE_RECOMMENDING_THIS_MORTGAGE_TYPE",
                        "WHY ARE WE RECOMMENDING THIS MORTGAGE TYPE?",
                    ),
                    (
                        "WHY_ARE_YOU_RECOMMENDING_THIS_TERM",
                        "WHY ARE WE RECOMMENDING THIS TERM?",
                    ),
                    (
                        "WHY_ARE_WE_RECOMMENDING_THIS_MORTGAGE_LENDER",
                        "WHY ARE WE RECOMMENDING THIS MORTGAGE LENDER?",
                    ),
                    (
                        "WHY_ARE_WE_RECOMMENDING_THIS_MORTGAGE_AMOUNT",
                        "WHY ARE WE RECOMMENDING THIS MORTGAGE AMOUNT?",
                    ),
                    ("WHAT_ARE_THE_COSTS_AND_FEES", "WHAT ARE THE COSTS AND FEES?"),
                    (
                        "WHAT_ARE_THE_DISADVANTAGES_AND_RISKS",
                        "WHAT ARE THE DISADVANTAGES AND RISKS?",
                    ),
                    (
                        "WHAT_IS_THE_COST_OF_OUR_ADVICE",
                        "WHAT IS THE COST OF OUR ADVICE?",
                    ),
                    ("WHAT_IS_THE_PROTECTION", "WHAT IS THE PROTECTION?"),
                    (
                        "WHAT_IS_THE_BUILDINGS_INSURANCE",
                        "WHAT IS THE BUILDINGS INSURANCE?",
                    ),
                    ("WHAT_IS_THE_WILLS", "WHAT IS THE WILLS?"),
                ],
                max_length=250,
                null=True,
            ),
        ),
    ]
