# Generated by Django 5.1.2 on 2025-05-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0086_alter_extraanswer_extra_answer_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extraanswer",
            name="extra_answer_choices",
        ),
        migrations.AddField(
            model_name="extraanswer",
            name="section_choices",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "YOUR_CIRCUMSTANCES_AND_OBJECTIVES",
                        "Your circumstances and objectives",
                    ),
                    ("BUDGET_AND_AFFORDABILITY", "Budget and affordability"),
                    ("NEW_MORTGAGE_DETAILS", "New mortgage details"),
                    (
                        "RECOMMENDED_REPAYMENT_METHOD",
                        "Why are we recommending this repayment method?",
                    ),
                    (
                        "RECOMMENDED_MORTGAGE_TYPE",
                        "Why are we recommending this mortgage type?",
                    ),
                    ("RECOMMENDED_TERM", "Why are we recommending this term?"),
                    (
                        "RECOMMENDED_LENDER",
                        "Why are we recommending this mortgage lender?",
                    ),
                    (
                        "RECOMMENDED_AMOUNT",
                        "Why are we recommending this mortgage amount?",
                    ),
                    ("COSTS_AND_FEES", "What are the costs and fees?"),
                    (
                        "DISADVANTAGES_AND_RISKS",
                        "What are the disadvantages and risks?",
                    ),
                    ("COST_OF_ADVICE", "What is the cost of our advice?"),
                    ("PROTECTION", "What is the protection?"),
                    ("BUILDINGS_INSURANCE", "What is the buildings insurance?"),
                    ("WILLS", "What is the wills?"),
                ],
                max_length=250,
                null=True,
            ),
        ),
    ]
