# Generated by Django 5.1.2 on 2025-05-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0087_remove_extraanswer_extra_answer_choices_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mortgageneeds",
            name="is_ability_to_add_fees_mortgage",
        ),
        migrations.RemoveField(
            model_name="mortgageneeds",
            name="notes",
        ),
        migrations.AddField(
            model_name="mortgageneeds",
            name="app_one_asu",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mortgageneeds",
            name="app_one_buildings_and_contents",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mortgageneeds",
            name="app_one_critical_illness",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mortgageneeds",
            name="app_one_family_income_benefit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mortgageneeds",
            name="app_one_income_protection",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mortgageneeds",
            name="app_one_life_cover",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mortgageneeds",
            name="app_one_pmi",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mortgageneeds",
            name="app_two_asu",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mortgageneeds",
            name="app_two_buildings_and_contents",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mortgageneeds",
            name="app_two_critical_illness",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mortgageneeds",
            name="app_two_family_income_benefit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mortgageneeds",
            name="app_two_income_protection",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mortgageneeds",
            name="app_two_life_cover",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mortgageneeds",
            name="app_two_pmi",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mortgageneeds",
            name="is_ability_to_add_fees_mortgage_extra_interest_will_be_payable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mortgageneeds",
            name="note_one",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="mortgageneeds",
            name="note_three",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="mortgageneeds",
            name="note_two",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
