# Generated by Django 5.1.2 on 2025-05-30 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0088_remove_mortgageneeds_is_ability_to_add_fees_mortgage_and_more"),
        ("organization", "0014_alter_networkuser_role_alter_organizationuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="network",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.network",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.organization",
            ),
        ),
    ]
