# Generated by Django 5.1.2 on 2025-06-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0089_case_network_alter_case_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="completed_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when case was completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="last_activity_date",
            field=models.DateTimeField(
                auto_now=True, help_text="Last activity on this case"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="submitted_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when case was submitted", null=True
            ),
        ),
    ]
