# Generated by Django 5.1.2 on 2025-07-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0090_case_completed_date_case_last_activity_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_stage",
            field=models.CharField(
                choices=[
                    ("ENQUIRY", "Enquiry"),
                    ("FACT_FIND", "Fact Find"),
                    ("RESEARCH_COMPLIANCE_CHECK", "Research and Compliance Check"),
                    ("DECISION_IN_PRINCIPLE", "Decision in Principle"),
                    ("FULL_MORTGAGE_APPLICATION", "Full Mortgage Application"),
                    ("OFFER_FROM_BANK", "Offer From Bank"),
                    ("LEGAL", "Legal"),
                    ("COMPLETION", "Completion"),
                    ("FUTURE_OPPORTUNITY", "Future Opportunity"),
                    ("NOT_PROCEED", "Not Proceed"),
                ],
                db_index=True,
                default="ENQUIRY",
                max_length=50,
            ),
        ),
    ]
