# Generated by Django 5.1.2 on 2025-08-06 06:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0092_case_assigned_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("adviser_name", models.CharField(max_length=100)),
                (
                    "is_clarification_explanation_of_the_service_firm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_timely_service_delivery",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_helpfulness_representative",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "the_firm_offices_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_accuracy_information_provided",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_clarification_explanation_paid",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_raising_queries_relating_service",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_clarification_explanation_protection_review",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_understanding_of_financial_objectives",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_explanation_consideration_of_attitude_risk",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_explanation_consideration_capacity_loss_of_capital",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_explanation_adviser_product",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_interaction_adviser_professionals",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_suitable_advice_for_your_needs",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_ability_of_the_adviser_undue_pressure_commit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_timing_deliver_review_by_adviser",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "the_broker_fee_paid_represents",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "explanation_broker_fees_including_refund_policy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_receive_the_value_expected_broker_fee",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_any_other_documentation_provided_to_you",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_timing_arrangements_made_conduct_review_with_you",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_frequency_communications_receive_from_firm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_relevance_communications_sent_to_the_firm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_raising_any_queries_on_communications",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_overall_standard_communications_received_from_firm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_timely_manner_of_receiving_letter_confirming_recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_THAN_EXPECTED", "BETTER_THAN_EXPECTED"),
                            ("AS_EXPECTED", "AS_EXPECTED"),
                            ("BELOW_EXPECTED", "BELOW_EXPECTED"),
                            ("N/A", "N/A"),
                            ("NOT_MENTIONED_TO_ME", "NOT_MENTIONED_TO_ME"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "do_we_better_serve_next_time",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "have_any_further_comments_on_the_service_received",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "do_you_like_someone_to_contact_you",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "YES"), ("NO", "NO")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_servey",
                        to="case.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
    ]
