# Generated by Django 5.1.2 on 2025-08-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0092_case_assigned_to"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employmentdetails",
            old_name="gross_annual_income",
            new_name="gross_monthly_income",
        ),
        migrations.RenameField(
            model_name="employmentdetails",
            old_name="net_annual_income",
            new_name="net_monthly_income",
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="date_of_name_change",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="intend_to_move_into_the_new_property",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="landlord_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="landlord_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="landlord_telephone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="rental_monthly_payment",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="case_completed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="case_offered_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="case_submitted",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="exchange_of_contracts_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="legals_instructed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="review_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="stage_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="valuation_booked_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="valuation_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="valuation_instructed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="valuation_received_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
