# Generated by Django 5.1.2 on 2025-08-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0093_clientsurvey"),
        (
            "case",
            "0093_rename_gross_annual_income_employmentdetails_gross_monthly_income_and_more",
        ),
    ]

    operations = []
