# Generated by Django 5.1.2 on 2025-08-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0094_merge_20250807_1957"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsurvey",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
