# Generated by Django 5.1.2 on 2025-08-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0095_alter_clientsurvey_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientsurvey",
            name="client_survey",
            field=models.BooleanField(default=False),
        ),
    ]
