# Generated by Django 5.1.2 on 2025-08-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0096_clientsurvey_client_survey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsurvey",
            name="adviser_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
