# Generated by Django 5.1.2 on 2025-08-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0097_alter_clientsurvey_adviser_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantdetails",
            name="landlord_address_line_one",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="landlord_address_postcode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="landlord_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="landlord_country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="landlord_county",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="landlord_house_number_or_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="new_address_address_one",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="new_address_address_two",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="new_address_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="new_address_house_number_or_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
