# Generated by Django 5.1.2 on 2025-08-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0098_applicantdetails_landlord_address_line_one_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantdetails",
            name="New_address_effective_form",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="new_address_country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="new_address_county",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="new_address_postcode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
