# Generated by Django 5.1.2 on 2025-08-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0099_applicantdetails_new_address_effective_form_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applicantdetails",
            old_name="New_address_effective_form",
            new_name="new_address_effective_form",
        ),
    ]
