# Generated by Django 5.1.2 on 2025-08-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "case",
            "0100_rename_new_address_effective_form_applicantdetails_new_address_effective_form",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="applicantdetails",
            old_name="new_address_effective_form",
            new_name="new_address_effective_from",
        ),
    ]
