# Generated by Django 5.1.2 on 2025-09-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0103_adverse_note_applicantdetails_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employmentdetails",
            name="other_income_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CARERS_ALLOWANCE", "CARER'S ALLOWANCE"),
                    ("CHILD_BENEFIT", "Child Benefit"),
                    (
                        "CHILD_MAINTENANCE_COURT_ORDERED",
                        "CHILD MAINTENANCE COURT ORDERED",
                    ),
                    (
                        "CHILD_MAINTENANCE_NON_COURT_ORDERED",
                        "CHILD_MAINTENANCE NON COURT ORDERED",
                    ),
                    ("CHILD_TAX_CREDITS", "CHILD TAX CREDITS"),
                    ("DISABILITY_LIVING_ALLOWANCE", "DISABILITY LIVING ALLOWANCE(DLA)"),
                    (
                        "EMPLOYMENT_AND_SUPPORT_ALLOWANCE(ESA)",
                        "EMPLOYMENT AND SUPPORT ALLOWANCE(ESA)",
                    ),
                    ("MAINTENANCE_INCOME", "MAINTENANCE INCOME"),
                    (
                        "PERSONAL_INDEPENDENCE_PAYMENTS(PIP)",
                        "PERSONAL INDEPENDENCE PAYMENTS (PIP)",
                    ),
                    ("MATERNITY_PAY", "MATERNITY PAY"),
                    ("PENSION_CREDIT", "PENSION CREDIT"),
                    ("RENTAL_INCOME", "RENTAL INCOME"),
                    ("WORKING_TAX_CREDITS", "WORKING TAX CREDITS"),
                    ("OTHER", "OTHER"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
