# Generated by Django 5.1.2 on 2025-09-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0104_alter_employmentdetails_other_income_source"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loandetails",
            old_name="other_note",
            new_name="other_lender_note",
        ),
    ]
