# Generated by Django 5.1.2 on 2025-09-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0105_rename_other_note_loandetails_other_lender_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employmentdetails",
            name="company_type",
        ),
        migrations.AddField(
            model_name="employmentdetails",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PERMANENT", "Permanent"),
                    ("CONTRACT", "Contract"),
                    ("TEMPORARY", "Temporary"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employmentdetails",
            name="business_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRIVATE_LIMITED", "Private Limited Company"),
                    ("PUBLIC_LIMITED", "Public Limited Company"),
                    ("SOLE_TRADER", "Sole Trader"),
                    ("PARTNERSHIP", "Partnership"),
                    ("LIMITED_LIABILITY_PARTNERSHIP", "Limited Liability Partnership"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
