# Generated by Django 5.1.2 on 2025-09-05 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0106_remove_employmentdetails_company_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PreviousAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("postcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "house_name_or_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("time_at_address_years", models.PositiveIntegerField(default=0)),
                ("time_at_address_months", models.PositiveIntegerField(default=0)),
                (
                    "residential_status",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("RENTING_PRIVATE", "Renting - private"),
                            ("RENTING_LOCAL_AUTHORITY", "Renting - Local Authority"),
                            ("TIED_ACCOMMODATION", "Tied Accommodation"),
                            ("LIVING_WITH_PARENTS", "Living with Parents"),
                            (
                                "LIVING_WITH_FRIENDS_FAMILY",
                                "Living with Friends/Family",
                            ),
                        ],
                        default="OWNER",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
