# Generated by Django 5.1.2 on 2025-09-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0106_remove_employmentdetails_company_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employmentdetails",
            name="other_income_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CARERS_ALLOWANCE", "Carer's Allowance"),
                    ("CHILD_BENEFIT", "Child Benefit"),
                    (
                        "CHILD_MAINTENANCE_COURT_ORDERED",
                        "Child Maintenance Court Ordered",
                    ),
                    (
                        "CHILD_MAINTENANCE_NON_COURT_ORDERED",
                        "Child Maintenance Non Court Ordered",
                    ),
                    ("CHILD_TAX_CREDITS", "Child Tax Credits"),
                    (
                        "DISABILITY_LIVING_ALLOWANCE",
                        "Disability Living Allowance (DLA)",
                    ),
                    (
                        "EMPLOYMENT_AND_SUPPORT_ALLOWANCE",
                        "Employment and Support Allowance (ESA)",
                    ),
                    ("MAINTENANCE_INCOME", "Maintenance Income"),
                    (
                        "PERSONAL_INDEPENDENCE_PAYMENTS",
                        "Personal Independence Payments (PIP)",
                    ),
                    ("MATERNITY_PAY", "Maternity Pay"),
                    ("PENSION_CREDIT", "Pension Credit"),
                    ("RENTAL_INCOME", "Rental Income"),
                    ("WORKING_TAX_CREDITS", "Working Tax Credits"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
