# Generated by Django 5.1.2 on 2025-09-05 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0107_previousaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="previousaddress",
            name="applicant_details",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="previous_addresses",
                to="case.applicantdetails",
            ),
            preserve_default=False,
        ),
    ]
