# Generated by Django 5.1.2 on 2025-09-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0108_previousaddress_applicant_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="previousaddress",
            name="complete_previous_address",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="previousaddress",
            name="time_at_address_months",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="previousaddress",
            name="time_at_address_years",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
