# Generated by Django 5.1.2 on 2025-09-08 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0109_previousaddress_complete_previous_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="previousaddress",
            old_name="effective_from",
            new_name="pre_effective_from",
        ),
        migrations.RenameField(
            model_name="previousaddress",
            old_name="effective_to",
            new_name="pre_effective_to",
        ),
    ]
