# Generated by Django 5.1.2 on 2025-09-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "case",
            "0110_rename_effective_from_previousaddress_pre_effective_from_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="previousaddress",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
