# Generated by Django 5.1.2 on 2024-11-07 12:17

import enumerify.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=enumerify.fields.SelectIntegerField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("DRAFT", "Draft"),
                    ("RELEASED", "Released"),
                    ("APPROVED_DRAFT", "Approved Draft"),
                    ("ABSENT", "Absent"),
                    ("PURCHASE_ORDER", "Purchase Order"),
                    ("SUSPEND", "Suspend"),
                    ("ON_HOLD", "On Hold"),
                    ("HARDWIRED", "Hardwired"),
                    ("LOSS", "Loss"),
                    ("FREEZE", "Freeze"),
                    ("FOR_ADJUSTMENT", "For Adjustment"),
                    ("DISTRIBUTOR_ORDER", "Distributor Order"),
                ],
                default="ACTIVE",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("LEAD", "Lead"),
                    ("CLIENT", "Client"),
                    ("INTRODUCER", "Introducer"),
                    ("SERVICE_HOLDER", "Service Holder"),
                ],
                default="LEAD",
                max_length=20,
            ),
        ),
    ]
