# Generated by Django 5.1.2 on 2024-11-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_status_alter_user_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="status",
        ),
    ]
