# Generated by Django 5.1.2 on 2024-11-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_user_organization_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=24, null=True
            ),
        ),
    ]
