# Generated by Django 5.1.2 on 2024-11-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_remove_user_organization_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("LEAD", "Lead"),
                    ("CLIENT", "Client"),
                    ("ADVISOR", "Advisor"),
                    ("INTRODUCER", "Introducer"),
                    ("SERVICE_HOLDER", "Service Holder"),
                ],
                default="LEAD",
                max_length=20,
            ),
        ),
    ]
