# Generated by Django 5.1.2 on 2024-12-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
    ]
