# Generated by Django 5.1.2 on 2025-02-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="user/profile"),
        ),
    ]
