# Generated by Django 5.1.2 on 2025-07-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="title",
            field=models.CharField(
                choices=[
                    ("MR", "Mr."),
                    ("MRS", "Mrs."),
                    ("MS", "Ms."),
                    ("DR", "Dr."),
                    ("MISS", "Miss."),
                    ("MADAM", "Madam."),
                    ("MAIDEN", "Maiden."),
                    ("PROFESSOR", "Professor."),
                    ("DOCTOR", "Doctor."),
                ],
                default="MR",
                max_length=64,
            ),
        ),
    ]
